// --- DATA: Chronologically Ordered Sets (Converted from paper 1.html) ---
const quizSets = [
    {
        setName: "Set 1",
        questions: [
            { q: "1. What are the sources of law?", o: ["Constitution of India", "Constitution of India, judicial precedents, customary laws, statutes and ordinance", "Statutes enacted by the Parliament of India and State Legislatures", "Religion"], c: "Constitution of India, judicial precedents, customary laws, statutes and ordinance" },
            { q: "2. Which Article in the Constitution of India, 1950 has provisions for introduction of a bill in the Parliament of India?", o: ["Article 119", "Article 141", "Article 107", "Article 243"], c: "Article 107" },
            { q: "3. Money Bill is introduced in which House of the Parliament?", o: ["Council of People Lok Sabha", "Council of States Rajya Sabha", "Both the Houses", "None of the Houses"], c: "Council of People Lok Sabha" },
            { q: "4. Under what Article of the Constitution of India, 1950 is The President of India empowered to make an Ordinance?", o: ["Article 243", "Article 123", "Article 129", "Article 368"], c: "Article 123" },
            { q: "5. The essence of Sub-Ordinate legislation can be found in which Article of the Constitution of India, 1950?", o: ["Article 12", "Article 32", "Article 13", "Article 14"], c: "Article 13" },
            { q: "6. When was the Constitution of India passed by the Constituent Assembly?", o: ["26th January 1950", "26th November 1949", "25th November 1949", "15th August 1947"], c: "26th November 1949" },
            { q: "7. Which is the highest Court in India?", o: ["High Court", "Supreme Court of India", "International Court of Justice", "Sessions Court"], c: "Supreme Court of India" },
            { q: "8. Which Articles of the Constitution of India have the power to entertain petitions of violation of Fundamental Right?", o: ["Article 32", "Article 226", "Article 226 and Article 32", "Article 356"], c: "Article 226 and Article 32" },
            { q: "9. Which is the highest civil court in a district?", o: ["Sessions Court", "Supreme Court of India", "District Court", "High Court"], c: "District Court" },
            { q: "10. Which Article of the Constitution of India empowers the legislature to make laws?", o: ["Article 12", "Article 243", "Article 141", "Article 245"], c: "Article 245" },
            { q: "11. When was the Supreme Court of India established?", o: ["26th November 1949", "26th January 1950", "28th January 1950", "1st October 1937"], c: "26th January 1950" },
            { q: "12. Which Article of the Constitution of India stipulates law made by the Supreme Court of India?", o: ["Article 141", "Article 245", "Article 368", "Article 352"], c: "Article 141" },
            { q: "13. What is the Schedule in the Constitution of India, for Separation of Subject for Legislature?", o: ["9th Schedule", "7th Schedule", "32nd Schedule", "14th Schedule"], c: "7th Schedule" },
            { q: "14. What kind of structure does the Indian Constitution have?", o: ["Unitary", "Federal", "Autocracy", "Totalitarian"], c: "Federal" },
            { q: "15. Under which Article can we amend the provisions of the Constitution of India?", o: ["Article 356", "Article 368", "Article 254", "Article 245"], c: "Article 368" }
        ]
    },
    {
        setName: "Set 2",
        questions: [
            { q: "16. Which is the lowest court to approach for criminal matters?", o: ["Munsif Court", "Judicial Magistrate", "Sessions Court", "District Court"], c: "Judicial Magistrate" },
            { q: "17. Mention the number of judges in the Supreme Court of India including Chief Justice of India currently.", o: ["23", "32", "34", "46"], c: "34" },
            { q: "18. Fundamental Rights are mentioned under which part of the Constitution of India?", o: ["Part-II", "Part-III", "Part-IX", "Part-XII"], c: "Part-III" },
            { q: "19. Municipalities are provided for authority under which part of the Constitution of India?", o: ["Part IX", "Part IXA", "Part III", "Part I"], c: "Part IXA" },
            { q: "20. Under what Article of the Constitution of India, 1950 is the Governor of a State empowered to make an Ordinance?", o: ["Article 123", "Article 243", "Article 245", "Article 213"], c: "Article 213" },
            { q: "21. What Are Personal Laws?", o: ["Laws relating to inter personal behaviour", "Customs (religious beliefs) that have now been codified", "Laws that a person makes", "Laws based on opinion"], c: "Customs (religious beliefs) that have now been codified" },
            { q: "22. Which Article of the Constitution of India, deal with inconsistency between laws made by Parliament and laws made by the Legislatures of States?", o: ["Article 245", "Article 254", "Article 368", "Article 32"], c: "Article 254" },
            { q: "23. What is the Private Bill?", o: ["A bill introduced by a member other than a Minister", "Bill introduced by a Private company", "Bill introduced by a private citizen", "A bill relating affairs which are private to individual"], c: "A bill introduced by a member other than a Minister" },
            { q: "24. The Parliament for the Union of India which shall consist?", o: ["The President, the Council of States (Rajya Sabha) and the House of the People (Lok Sabha)", "Rajya Sabha", "Lok Sabha", "Legislative Assembly"], c: "The President, the Council of States (Rajya Sabha) and the House of the People (Lok Sabha)" },
            { q: "25. Secondary/Sub-ordinate legislation cannot go beyond:", o: ["The ambit of the Act", "The ambit of the Act or the Constitution of India", "The Constitution of India.", "Directive Principles of State Policy"], c: "The ambit of the Act or the Constitution of India" },
            { q: "26. The Appellate court for National consumer disputes redressal communication tribunal is", o: ["High Court", "district courts/Subordinate court", "court of subordinate judge class-1", "supreme court"], c: "supreme court" },
            { q: "27. The ancient Indian courts can be evided into six categories based on their rank as:", o: ["The Gana-The Kula-The Shreni The Nripa - the Adhikrita - The Sasita", "The Kula - The Shreni The Gana - the Adhikrita - The sasita - The Nripa", "The Kula-the Adhikrita The Gana the Adhikrita - The sasita The Nripa- The shreni", "The Nripa-the Adhikrita- The Kula The Gana-The shreni The sasita"], c: "The Kula - The Shreni The Gana - the Adhikrita - The sasita - The Nripa" },
            { q: "28. Voidable contract is one:", o: ["Which is lawful", "Which is invalid", "Which is valid so long it is not avoided by the party entitled to do so", "None of these"], c: "Which is valid so long it is not avoided by the party entitled to do so" },
            { q: "29. The difference between an advertisement for sale and a proposal is", o: ["No difference at all", "That a proposal becomes a promise as soon as the party to whom it is made accepts it but an advertisement does not", "Every case will be viewed according to the circumstances", "None of these"], c: "That a proposal becomes a promise as soon as the party to whom it is made accepts it but an advertisement does not" },
            { q: "30. In a Book depot a catalogue of books enlisting the price of each book and specifying the place where the particular book is available is:", o: ["An invitation to offer", "An offer", "An invitation to visit the book shop", "None of these"], c: "An invitation to visit the book shop" }
        ]
    },
    {
        setName: "Set 3",
        questions: [
            { q: "31. A catalogue of the goods of a company for sale..... a series of offers but only an invitation for offers.", o: ["is", "is not", "in normal cases is", "in normal cases is not"], c: "is not" },
            { q: "32. An offer does not lapse if the:", o: ["offeror dies before acceptance", "The offeree dies before acceptance", "Acceptance is made by the offeree in ignorance of the death of the offeror", "Acceptance is made by the offeree with knowledge of the death of the offeror"], c: "Acceptance is made by the offeree in ignorance of the death of the offeror" },
            { q: "33. A telephonic acceptance is complete when the offer is:", o: ["spoken into the telephone", "heard but not understood by the offeror", "heard and understood by the offeror", "is received, heard and understood by some person in the offeror's house"], c: "heard and understood by the offeror" },
            { q: "34. With regard to the contractual capacity of a person of unsound mind, which one of the following statements is most appropriate?", o: ["A person of unsound mind can never enter into a contract", "A person of unsound mind can enter into a contract", "A person who is usually of unsound mind can contract when he is, at the time of entering into a contract, of sound mind", "A person who is occasionally of unsound mind can contract although at the time of making the contract, he is of unsound mind"], c: "A person who is usually of unsound mind can contract when he is, at the time of entering into a contract, of sound mind" },
            { q: "35. While obtaining the consent of the promisee, keeping silence by the promisor when he has a duty to speak about the material facts, amounts to consent obtained by:", o: ["Coercion", "Misrepresentation", "Mistake", "Fraud"], c: "Fraud" },
            { q: "36. 'A' threatened to commit suicide if his wife did not execute a sale deed in favour of this brother. The wife executed the sale deed. This transaction is:", o: ["Voidable due to under influence", "Voidable due to coercion", "Void being immoral", "Void being forbidden by law"], c: "Voidable due to coercion" },
            { q: "37. A contract which is vitiated by undue influence is declared as which one of the following by the Indian Contract Act?", o: ["Invalid", "Void", "Illegal", "Voidable"], c: "Voidable" },
            { q: "38. Consider the following: 1. Active concealment of fact. 2. Promise made without any intention of performing it. 3. Breach of duty which gains an advantage to the person committing it. 4. Inducing mistakes as to subject matter. Which of the above amount to fraud?", o: ["1 and 2", "2 and 3", "3 and 4", "1 and 4"], c: "1 and 2" },
            { q: "39. Factors vitiating consent are:", o: ["Coercion, Undue influence", "Fraud, Misrepresentation", "Mistake", "All of these"], c: "All of these" },
            { q: "40. Misrepresentation means:", o: ["Unwarranted assertion", "Any breach of duty without an intent to deceive", "Innocent mistake", "All the above"], c: "All the above" },
            { q: "41. If a party stands in a fiduciary relation to the other:", o: ["He cannot dominate", "He can dominate the will of another", "The trust should be maintained", "None of these"], c: "He can dominate the will of another" },
            { q: "42. A person is deemed to be in a position to dominate the will of another if he:", o: ["Holds real or apparent authority", "Stands in a fiduciary relationship", "Both 1 and 2", "Either 1 or 2"], c: "Both 1 and 2" },
            { q: "43. If both the parties to a contract believe in the existence of a subject, which in fact does not exist, the agreement would be:", o: ["Unenforceable", "Void", "Voidable", "None of these"], c: "Void" },
            { q: "44. For a valid contract:", o: ["Both the parties should have given their consent", "The consent should be free", "Both 1 and 2", "Either 1 or 2"], c: "Both 1 and 2" },
            { q: "45. When both the parties to an agreement are under a mistake as to a matter of fact essential to an agreement, the agreement is:", o: ["Void", "Valid", "Voidable", "Illegal"], c: "Void" }
        ]
    },
    {
        setName: "Set 4",
        questions: [
            { q: "46. In Indian Contract Act, the term consensus ad idem means:", o: ["Parties under a mistake", "Parties under the free consent", "Parties agreeing upon the same thing in same sense", "None of these"], c: "Parties agreeing upon the same thing in same sense" },
            { q: "47. To prove undue influence, the plaintiff has to prove that:", o: ["The relations, subsisting between the parties are such that the defendant was in a position to dominate the will of the plaintiff", "The defendant used that position to obtain an unfair advantage from the plaintiff", "Both 1 and 2", "None of these"], c: "Both 1 and 2" },
            { q: "48. The validity of contract is not affected by:", o: ["Mistake of fact", "Mistake of Indian law", "Misrepresentation", "Fraud"], c: "Mistake of Indian law" },
            { q: "49. Unlawful agreements comprise:", o: ["Illegal agreements", "Immoral agreements only", "Agreements opposed to public policy only", "All the agreements mentioned above"], c: "All the agreements mentioned above" },
            { q: "50. The exceptions to the rule that an agreement in restraint of trade is void, are contained in:", o: ["The provisions of Sec. 27 of the Contract Act only", "Secs. 11, 36, 54 and 55 of the partnership Act only", "Both the above mentioned provisions of the Contract Act & Partnership Act respectively", "None of the above provisions"], c: "The provisions of Sec. 27 of the Contract Act only" },
            { q: "51. A contract to trade with an enemy is:", o: ["an immoral agreement", "a valid agreement", "an agreement opposed to public policy", "an enforceable agreement"], c: "an agreement opposed to public policy" },
            { q: "52. An agreement will be unlawful if:", o: ["There is no consent", "Consent is not free", "There is no consideration", "The object is forbidden by law"], c: "The object is forbidden by law" },
            { q: "53. In a wagering agreement:", o: ["Both the parties win", "Both the parties lose", "None of the parties wins", "One party wins and the other looses"], c: "One party wins and the other looses" },
            { q: "54. Which one of the following statements is correct?", o: ["Void agreements are always illegal", "Illegal agreements are voidable", "Illegal agreement can be ratified by the parties", "Illegal agreements are always void"], c: "Illegal agreements are always void" },
            { q: "55. Which one of the following is not a wagering agreement?", o: ["A lottery", "An agreement to buy a ticket for a lottery", "Commercial transaction, the intention of which is not to deliver the goods but only to pay the difference in price", "A contract of insurance"], c: "A contract of insurance" },
            { q: "56. A wagering agreement in India is declared by the Contract Act as:", o: ["Illegal and void", "Void but not illegal", "Voidable at the option of the aggrieved party", "Immoral"], c: "Void but not illegal" },
            { q: "57. Which one of the following is a void agreement?", o: ["An agreement without consideration", "An agreement in restraint of marriage", "An agreement in restraint of trade", "All of the above"], c: "All of the above" },
            { q: "58. An agreement which restricts a person's freedom to marry or to marry any person of his choice is against public policy and is:", o: ["Lawful", "Illegal", "Void", "None of these"], c: "Void" },
            { q: "59. An agreement of service under which an employee agrees that he will serve a particular employer for a certain duration and that he will not serve anybody else during that period, is:", o: ["Valid agreement", "Void agreement", "Illegal agreement", "None of these"], c: "Valid agreement" },
            { q: "60. If the seller agrees to supply all the goods produced by him to a certain buyer and to nobody else, and the buyer also, in turn undertakes to accept the whole of the quantity, the agreement is:", o: ["Void agreement", "Solus agreement", "Illegal agreement", "None of these"], c: "None of these" }
        ]
    },
    {
        setName: "Set 5",
        questions: [
            { q: "61. M, who is a dealer in mustard oil only, agrees to sell to N '500 litres of oil'. This agreement is:", o: ["Valid contract", "Void contract", "Voidable contract", "Unenforceable contract"], c: "Valid contract" },
            { q: "62. A and B agree that A shall pay ₹1,000 for which B shall afterwards deliver to an either rice or smuggled opium. In this case:", o: ["The first agreement is void and the second voidable", "The first is voidable and the second is void", "The first is valid and the second is void", "The first is void and the second is valid"], c: "The first is valid and the second is void" },
            { q: "63. A agrees to sell to B a 'hundred tons of oil'. There is nothing whatever to show what kind of oil was intended. The agreement is:", o: ["Valid", "Void for uncertainty", "Voidable", "Illegal"], c: "Void for uncertainty" },
            { q: "64. A agrees to sell to B 'my white horse for ₹500 or ₹1,000'. There is nothing to show which of the two prices was to be given. The agreement is:", o: ["Valid", "Void", "Voidable", "Unenforceable"], c: "Void" },
            { q: "65. Agreements between a husband and wife living in friendly environment are:", o: ["Valid contracts", "A void contracts", "Domestic arrangements", "Voidable contract"], c: "Domestic arrangements" },
            { q: "66. A promised to marry none else than Miss B and in default to pay her a sum of ₹1,000. Subsequently A married Miss C and Miss B sued for recovery of ₹1,000. The contract is:", o: ["Valid", "Void", "Voidable", "Enforceable"], c: "Void" },
            { q: "67. A promises B to pay ₹100 if it rains on Monday, and B promises A to pay 100 if it does not rain on Monday. This agreement is:", o: ["a valid agreement", "a voidable agreement", "a wagering agreement", "an illegal agreement"], c: "a wagering agreement" },
            { q: "68. P engages B to kill C and borrows ₹100 from D to pay B. If D is aware of the purpose of the loan, the transaction is:", o: ["Valid", "Void", "Illegal", "Not enforceable"], c: "Illegal" },
            { q: "69. A leaves a firm doing a particular business in Mumbai. He agrees with the other partners of the firm not to start a similar business as that of the firm in and around Mumbai for 3 years. This agreement is:", o: ["Valid", "Immoral", "Illegal", "Void"], c: "Void" },
            { q: "70. A, while filling up the insurance application form, states his age as 25 believing it to be true. His actual age was 27. The Life Insurance Corporation issued a policy in his favour charging a lower premium than what it should have charged if the actual age had been given. This is a case of:", o: ["Fraud", "Misrepresentation", "Undue influence", "Mistake of fact"], c: "Misrepresentation" },
            { q: "71. B, having discovered a vein of ore on the estate of A, adopts means to conceal, and does conceal, the existence of the ore from A. Owing to A's ignorance B is enabled to buy the estate at a low-price. The contract is:", o: ["Valid", "Void", "Voidable at the option of A", "Invalid"], c: "Voidable at the option of A" },
            { q: "72. B let a cabin on hire to P a prostitute, knowing that it would be used for immoral purposes. The agreement is:", o: ["Enforceable", "Valid", "Voidable", "Void"], c: "Void" },
            { q: "73. A enters into an agreement with B who has robbed A of ₹10,000 to drop prosecution against him (B) in consideration of B's returning 8,000. Afterwards B refused to pay. A can get from B", o: ["8,000", "100", "Nothing", "10,000 plus damages"], c: "Nothing" },
            { q: "74. A agrees with B to discover treasure by magic for a consideration of ₹500. This is :", o: ["A void agreement", "A void contract", "A valid agreement", "An unenforceable contract"], c: "A void agreement" },
            { q: "75. X, a tailor, employed Y as his assistant under an agreement that Y, on termination of his employment shall not start the business of a tailor. This restraint is:", o: ["Void", "Valid", "Illegal", "Voidable"], c: "Void" }
        ]
    },
    {
        setName: "Set 6",
        questions: [
            { q: "76. X leaves a firm doing a particular business in Delhi. He agrees with other partners of the firm not to start a similar business as that of the firm in Delhi for 2 years. This agreement is:", o: ["Void", "Valid", "Voidable at X's option", "Invalid"], c: "Valid" },
            { q: "77. X promises to supply Y one tola of gold brought from the sun. This is:", o: ["a valid contract", "an illegal contract", "a void agreement", "a voidable agreement"], c: "a void agreement" },
            { q: "78. A promises B not to carry on a similar business as that of B if B pays him a certain amount. B pays the money but A continues to carry on the business. B can:", o: ["Do nothing", "Compel A to stop the business", "Get him imprisoned for fraud", "Sue A for damages"], c: "Do nothing" },
            { q: "79. A purchases B's business of selling neckties in Delhi. A can restrain B from:", o: ["Doing the business of selling neckties again in his life", "Doing any business in Delhi", "Doing the business of selling neckties in Delhi for a limited period", "None of the above"], c: "Doing the business of selling neckties in Delhi for a limited period" },
            { q: "80. A promised to marry B and none else and promised her to pay a sum of ₹5,000 in addition to what he gets from the other party if he marries someone else. A marries C and gets ₹10,000 from C. B can get from A:", o: ["5,000", "10,000", "Nothing", "5,000 plus damages"], c: "Nothing" },
            { q: "81. A promised B to obtain an employment for him in a public office. B promised to pay ₹2,000 to A for this. B gets a job through A but refuses to pay the money. A can:", o: ["Challenge B's appointment on the ground of non-payment of money", "Sue B for 2,000", "Do nothing", "Do both given at 1 and 2"], c: "Do nothing" },
            { q: "82. A, a Hindu already married with a living wife B, enters into a marriage agreement with a widow of 30 years of age. This agreement is:", o: ["Void, because of being opposed to public policy", "Valid and can be enforced by either party", "Voidable, because A has obtained B's consent by exercising undue influence against her", "Void, because of being forbidden by law"], c: "Void, because of being forbidden by law" },
            { q: "83. Rajeev entered into a contract with Lata to marry her on a fixed date. However, before the marriage date. Rajeev went mad. With reference to the Indian Contract Act which is the valid response?", o: ["Lata can't marry till Rajeev dies", "The executers of Rajeev can enforce the contract against Lata", "The contract becomes void", "All the statements are correct"], c: "The contract becomes void" },
            { q: "84. A and B agree to deal in smuggled goods and share the profits. A refuses to give B's share of profit. In this case:", o: ["B can enforce the agreement in the court.", "B can only claim damages.", "B has no remedy as the contract is illegal.", "B can enforce the contact or claim damages"], c: "B has no remedy as the contract is illegal." },
            { q: "85. A and B agree that law of limitation shall not apply to them. A debt becomes time barred and A refuses to pay the amount. Can B recover the amount under the terms of the agreement?", o: ["yes, the agreement between them is valid and enforceable.", "yes, the agreement is not opposed to public policy.", "no, the agreement is a voidable agreement and can be avoided by A.", "no, the agreement falls under section 23 and hence void"], c: "no, the agreement falls under section 23 and hence void" },
            { q: "86. A borrows ₹5,000 from B to purchase a revolver to shoot C. Can B recover his loan of ₹5,000.", o: ["yes, the agreement between them is valid and enforceable.", "yes, the agreement is not opposed to public policy.", "no, the agreement is a voidable agreement and can be avoided by A.", "no, the agreement falls under section 23 and hence void"], c: "no, the agreement falls under section 23 and hence void" },
            { q: "87. A borrows from B ₹500 to bet with C. Can B recover the amount of his loan?", o: ["yes, the agreement between them is collateral to a wagering agreement and hence enforceable", "yes, the agreement is not opposed to public policy", "no, the agreement is a voidable agreement and can be avoided by A", "no, the agreement is wagering agreement and falls under section 23 and hence void"], c: "no, the agreement is wagering agreement and falls under section 23 and hence void" },
            { q: "88. A paid 500 to a Government servant to get him a contract for the canteen. The Government servant could not get the contract. Can A recover 500 paid by him to the Government servant?", o: ["yes, the agreement between them is valid and enforceable", "yes, the agreement is not opposed to public policy", "no, the agreement is a voidable agreement and can be avoided by A", "no, the agreement is void"], c: "no, the agreement is void" },
            { q: "89. A person contracted to deliver a part of a specific crop of potatoes. The potatoes were destroyed by blight though no fault of the party. The contract is", o: ["Valid", "Voidable", "Void due to frustration of contract", "Illegal"], c: "Void due to frustration of contract" },
            { q: "90. A contracts to sing for B at a concert for ₹1,000 which are paid in advance. A is too ill to sing. Which of the following options is correct?", o: ["A is bound to make compensation", "A is not bound to make compensation to B for the loss of the profit which B would have made if A had been able to sing, but must refund to B ₹1,000 paid in advance", "A is not liable to refund to B ₹1,000 paid in advance", "A is liable for loss of profit as well as for refund"], c: "A is not bound to make compensation to B for the loss of the profit which B would have made if A had been able to sing, but must refund to B ₹1,000 paid in advance" }
        ]
    },
    {
        setName: "Set 7",
        questions: [
            { q: "91. A contractor entered into an agreement with Government to construct a godown and received advance payments for the same. He did not complete the work and the Government terminated the contract.", o: ["The Government can claim damages", "The Government under sec. 65 could recover the amount advanced to the contractor", "The Government cannot claim damages", "Both 1 & 2"], c: "Both 1 & 2" },
            { q: "92. Which one of the following has the correct sequence?", o: ["Offer, acceptance, contract, consideration.", "Offer, acceptance, consideration, contract", "Contract, acceptance, consideration, offer", "Offer, consideration, acceptance, contract."], c: "Offer, acceptance, consideration, contract" },
            { q: "93. A telephonic acceptance is complete when the offer is", o: ["spoken into the telephone.", "heard but not understood by the offeror.", "heard and understood by the offeror", "received, heard and understood by some person in the offeror's house."], c: "received, heard and understood by some person in the offeror's house." },
            { q: "94. In case of appropriation of goods, which are the essential requirements:", o: ["The goods should confirm to the description and quality stated in the contract.", "The goods must be in a deliverable state", "The appropriation must be by the seller with the assent of the buyer", "All the above"], c: "All the above" },
            { q: "95. Appropriation of goods means:", o: ["separating the goods sold from other goods", "putting the quantity of goods sold in suitable receptacles", "delivering the goods to the carrier or other bailee for the purpose of transmission to the buyer with reserving the right of disposal", "all the above"], c: "all the above" },
            { q: "96. The general rule of Sale of Goods Act is, risk prima facie passes with:", o: ["Ownership", "Possession", "Delivery", "Custody"], c: "Ownership" },
            { q: "97. 'Nemo dat quad non habet', means:", o: ["no one is greater than god", "none can give who does not himself possess", "every one can give everything he has", "everyone is bound by is habit"], c: "none can give who does not himself possess" },
            { q: "98. Transfer of documents of title to the goods sold to the buyer, amounts to:", o: ["actual delivery", "symbolic delivery", "constructive delivery", "none of these"], c: "symbolic delivery" },
            { q: "99. Under Sec.2(4) of the Sale of Goods Act, a delivery order enabling a person to obtain delivery on payment of price is:", o: ["Deemed as a Document of Title", "Not a Document of Title", "Document enabling title to Goods", "Not a valid document at all"], c: "Deemed as a Document of Title" },
            { q: "100. A Share Certificate is a", o: ["Document of Title to Goods", "Bill of Exchange", "Document Showing Title to Goods", "Instrument of Transfer"], c: "Document Showing Title to Goods" },
            { q: "101. A Bill of Lading is a -", o: ["Bill of Exchange", "Promissory Note", "Cheque", "Document of Title to Goods"], c: "Document of Title to Goods" },
            { q: "102. Section 19 of the Sale of Goods Act, deals with passing of property of..........goods.", o: ["Unascertained Goods", "Future Goods", "Specific or Ascertained Goods", "Contingent Goods"], c: "Specific or Ascertained Goods" },
            { q: "103. Voluntary transfer of possession from one person to another is called as:", o: ["Ownership", "Delivery", "Gift", "License"], c: "Delivery" },
            { q: "104. Which of the statement is incorrect in connection with duties of seller and buyer:", o: ["It is the duty of the seller to deliver the goods", "It is the duty of the buyer to accept and pay for them", "It is not the duty of the seller to deliver the goods", "It is the duty of the buyer to take delivery of goods"], c: "It is not the duty of the seller to deliver the goods" },
            { q: "105. Delivery of goods means-", o: ["Voluntary transfer of possession", "Compulsory transfer of possession", "Exchange of goods", "Voluntary transfer of ownership"], c: "Voluntary transfer of ownership" }
        ]
    },
    {
        setName: "Set 8",
        questions: [
            { q: "106. For a valid contract of sale, delivery may be:", o: ["Actual delivery", "Symbolic delivery", "Constructive delivery", "All of these"], c: "All of these" },
            { q: "107. Delivery of the keys of a godown where goods are kept amounts to:", o: ["Actual delivery", "Symbolic delivery", "Constructive delivery", "All of these"], c: "Symbolic delivery" },
            { q: "108. There are..........modes of delivery.", o: ["Three", "Two", "Four", "Five"], c: "Three" },
            { q: "109. The term 'Unpaid Seller' includes", o: ["Agent of the Buyer", "Agent of the Seller", "Agent of the Carrier/Transporter", "All of the above"], c: "Agent of the Seller" },
            { q: "110. The term 'Unpaid Seller' includes -", o: ["Buyer's agent to whom the Bill of Lading is endorsed", "Buyer's agent to whom the goods have been delivered", "Seller's agent to whom the Bill of Lading is endorsed", "Seller's agent to whom the goods have been delivered"], c: "Seller's agent to whom the Bill of Lading is endorsed" },
            { q: "111. Unpaid Seller can exercise his right of lien", o: ["even when property in goods has passed to the Buyer", "only when property in goods has not passed to the Buyer", "either 1 or 2", "neither 1 nor 2"], c: "even when property in goods has passed to the Buyer" },
            { q: "112. Unpaid Seller can exercise his right of re-sale of goods-", o: ["even when property in goods has passed to the Buyer", "only when property in goods has not passed to the Buyer", "either 1 or 2", "neither 1 nor 2"], c: "even when property in goods has passed to the Buyer" },
            { q: "113. Unpaid Seller can exercise his right of withholding delivery of goods", o: ["even when property in goods has passed to the Buyer", "only when property in goods has not passed to the Buyer", "either 1 or 2", "neither 1 nor 2"], c: "even when property in goods has passed to the Buyer" },
            { q: "114. The doctrine of Caveat emptor is not applicable", o: ["in case of sale under a patent name.", "in case of sale under a trade name.", "where the seller is guilty of fraud", "where the buyer relies on the skill and judgement of the seller"], c: "where the seller is guilty of fraud" },
            { q: "115. Property in the goods in the Sale of Goods Act, 1930 means", o: ["Ownership of goods", "Possession of goods", "Asset in the goods", "Custody of goods"], c: "Ownership of goods" },
            { q: "116. The Sale of Goods Act, 1930 governs the transfer of property in", o: ["movable property", "immovable property", "both movable and immovable property", "all types of properties"], c: "movable property" },
            { q: "117. A valid contract of sale", o: ["includes 'an agreement to sell'", "does not include 'an agreement to sell'", "includes hire purchase contract", "Includes contract for work and labour"], c: "includes 'an agreement to sell'" },
            { q: "118. The undertaking contained in a promissory note, to pay a certain sum of money is:", o: ["Conditional", "Unconditional", "may be conditional or unconditional depending upon the circumstances", "none of the above"], c: "Unconditional" },
            { q: "119. A bill of exchange contains a/an:", o: ["unconditional undertaking", "unconditional order", "conditional undertaking", "conditional order"], c: "unconditional order" },
            { q: "120. Cheque is a", o: ["promissory note", "bill of exchange", "both (a) and (b) above", "None of the above"], c: "bill of exchange" }
        ]
    },
    {
        setName: "Set 9",
        questions: [
            { q: "121. The term 'Negotiable instrument' is defined in the Negotiable Instruments Act, 1881, under section:", o: ["12", "13", "13A", "2(d)"], c: "13" },
            { q: "122. The term 'negotiation' in section 14 of the Negotiable Instruments Act, 1881 refers to:", o: ["the transfer of a bill of exchange, promissory note or cheque to any person, so as to constitute the person the holder thereof", "the payment by a bank on a negotiable instrument after due verification of the instrument", "the bargaining between the parties to a negotiable instrument", "all of the above"], c: "the transfer of a bill of exchange, promissory note or cheque to any person, so as to constitute the person the holder thereof" },
            { q: "123. If a minor draws, endorses, delivers or negotiates an instrument, such instrument binds:", o: ["all parties to the instrument including the minor", "only the minor and not other parties to the instrument", "all parties to the instrument except the minor", "none of the above"], c: "all parties to the instrument except the minor" },
            { q: "124. In a promissory note, the amount of money payable :", o: ["must be certain", "may be certain or uncertain", "is usually uncertain", "none of the above"], c: "must be certain" },
            { q: "125. A cheque is crossed ______ when it bears across its face an addition of the name of a banker, either with or without the words 'not negotiable'.", o: ["Specially", "General", "Restrictive", "None of the above"], c: "Specially" },
            { q: "126. Under section 118 of the Negotiable Instruments Act, 1881, it is presumed, until the contrary is proved, that every transfer of a negotiable instrument was made:", o: ["after its maturity", "before its maturity", "at its maturity", "none of the above"], c: "before its maturity" },
            { q: "127. Who among the following cannot cross a cheque?", o: ["Drawer", "Holder", "Banker", "Foreigner"], c: "Foreigner" },
            { q: "128. Where a cheque is crossed generally the banker on whom it is drawn:", o: ["shall not pay it otherwise than to a banker", "shall not pay it otherwise than to the holder", "shall not pay it to a banker", "none of the above"], c: "shall not pay it otherwise than to a banker" },
            { q: "129. The Negotiable Instrument Act is applicable to", o: ["Whole of India", "Whole of India except JK state", "Whole of India except J & Kashmir city", "None of the above"], c: "Whole of India" },
            { q: "130. The Negotiable Instruments Act, 1881 came into force on:", o: ["9th December, 1881", "19th December, 1881", "1st March, 1882", "None of the above"], c: "1st March, 1882" },
            { q: "131. The term Negotiable instrument is defined in section _____ of the Negotiable Instrument Act, 1881", o: ["2", "13", "12", "10"], c: "13" },
            { q: "132. Which of these is not a negotiable Instrument as per the Negotiable Instrument Act, 1881", o: ["Bill of exchange", "Delivery note", "Bearer Cheque", "Share certificate"], c: "Share certificate" },
            { q: "133. ______ is not a negotiable instrument as per customs and usage:", o: ["Delivery note", "Railway Receipt", "Cheque", "Government promissory note"], c: "Cheque" },
            { q: "134. An instrument incomplete in one way or other is called:", o: ["Inchoate Instrument", "Ambiguous instrument", "Foreign Instrument", "Dishonored Instrument"], c: "Inchoate Instrument" },
            { q: "135. A bill of exchange contains a/an", o: ["unconditional undertaking", "unconditional order", "conditional undertaking", "conditional order."], c: "unconditional order" }
        ]
    },
    {
        setName: "Set 10",
        questions: [
            { q: "136. A Corporation can be party to a Negotiable Instrument if", o: ["authorized by its article of association", "if special permission of Board of Directors taken", "if special resolution by Share holders is passed", "absolutely without any restrictions"], c: "authorized by its article of association" },
            { q: "137. The grace period for payment of a negotiable instrument other than payable on demand is days/months", o: ["7days", "3 days", "1 month", "15 days"], c: "3 days" },
            { q: "138. The term 'a cheque in the electronic form' is defined in the Negotiable Instruments Act, 1881 under:", o: ["Section 6(a)", "Section 6(1)(a)", "Explanation 1(a) of Section 6", "Section 6A"], c: "Explanation 1(a) of Section 6" },
            { q: "139. How many parties are involved in a Bill of Exchange:", o: ["2", "3", "4", "5"], c: "3" },
            { q: "140. A promissory note, bill of exchange or cheque drawn or made in India and made payable in, or drawn upon any person resident in, India is treated as a/an-", o: ["Inland instrument", "Local instrument", "Foreign instrument", "Indigenous instrument"], c: "Inland instrument" },
            { q: "141. If an instrument may be construed either as a promissory note or bill of exchange, it is--", o: ["a valid instrument", "ambiguous instrument", "a returnable instrument", "none of the above."], c: "ambiguous instrument" },
            { q: "142. If the words 'not negotiable' are used with special crossing in a cheque, the cheque is---", o: ["not transferable", "transferable", "negotiable under certain circumstances", "none of the above."], c: "not transferable" },
            { q: "143. Under Section 118 of the Negotiable Instruments Act, 1881, it is presumed, until the contrary is proved, that every transfer of a negotiable instrument was made:", o: ["after its maturity", "before its maturity", "at its maturity", "none of the above"], c: "before its maturity" },
            { q: "144. When an Instrument is drawn conditionally or for a special purpose as a collateral security and not for the purpose of transferring property therein, it is called an", o: ["Escrow Instrument", "Inchoate Instrument", "Ambigous Instrument", "None of the above"], c: "Escrow Instrument" },
            { q: "145. When a cheque is payable across the counter of a bank it is called", o: ["OTC cheque", "Open cheque", "Crossed Cheque", "Restricted cheque"], c: "Open cheque" },
            { q: "146. A Promissory Note must be", o: ["in writing", "unconditional", "signed by the maker", "all of the above"], c: "all of the above" },
            { q: "147. Communication that originates at a lower level and flows to a higher level is called -", o: ["Upward Communication", "Diagonal Communication", "Downward Communication", "None of the above"], c: "Upward Communication" },
            { q: "148. Communication among employees at the same level in the organizational structure is called -", o: ["Grapevine Communication", "Diagonal Communication", "Lateral Communication", "None of the above"], c: "Lateral Communication" },
            { q: "149. Which of the following should be avoided in the Group discussion?", o: ["Positive body language", "Leadership initiative", "False statements", "Confidence"], c: "False statements" },
            { q: "150. Which business communication usage provides a bird's eye view on a matter?", o: ["Speech", "Group Discussion", "Debate", "Presentation"], c: "Presentation" }
        ]
    },
    {
        setName: "Set 11",
        questions: [
            { q: "151. How many types of communication takes place in an organisation?", o: ["5", "1", "3", "4"], c: "4" },
            { q: "152. In which business communication, a speaker has to clearly speak for or against a topic?", o: ["Presentation", "Debate", "Speech", "Group discussion"], c: "Debate" },
            { q: "153. Includes face to face interaction with customers for closing the sale?", o: ["Sales promotion", "Advertising", "Direct marketing", "Personal Selling"], c: "Personal Selling" },
            { q: "154. Use of coupons and samples come under which mode of marketing communication?", o: ["Sales promotion", "Advertising", "Direct marketing", "Personal Selling"], c: "Sales promotion" },
            { q: "155. What is the situation called when a bad image of the company is created?", o: ["Positive PR", "Negative PR", "Customer service", "Promotion"], c: "Negative PR" },
            { q: "156. Business communications help in establishing _____ when marketing?", o: ["Professionalism", "Rudeness", "Negaitivity", "Casualness"], c: "Professionalism" },
            { q: "157. Participants involved in the process of communication must be", o: ["Judgemental", "Open-minded", "Both 1 and 2", "None of the above"], c: "Open-minded" },
            { q: "158. Which of the following is not one of the 8C's of communication?", o: ["Curiousness", "Conciseness", "Considerate", "Concreteness"], c: "Curiousness" },
            { q: "159. Need of proper grammar and syntax comes under which C of communication?", o: ["Completeness", "Coherence", "Courteous", "Correctness"], c: "Correctness" },
            { q: "160. If a message is short and to the point, the message is said to be", o: ["Correct", "Concise", "Coherent", "Complete"], c: "Concise" },
            { q: "161. The way the information is described or translated into a message and put in verbal or non-verbal medium is called", o: ["Feedback", "Decoding", "Encoding", "None of the above"], c: "Encoding" },
            { q: "162. Affirming comments with regard to future behaviour is called", o: ["Positive Feedback", "Negative Feedforward", "Positive Feedforward", "Decoding"], c: "Positive Feedforward" },
            { q: "163. Corrective comments with regard to past behaviour", o: ["Encoding", "Positive Feedback", "Negative Feedforward", "Negative Feedback"], c: "Negative Feedback" },
            { q: "164. Interpretation and conversion of information communicated into the intelligible form so that the recipient can fully understand the true meaning of the information is called", o: ["Decoding", "Encoding", "Feedback", "None of the above"], c: "Decoding" },
            { q: "165. What is the first step of communication process?", o: ["Encoding", "Transmitting", "Decoding", "Developing an idea"], c: "Encoding" }
        ]
    },
    {
        setName: "Set 12",
        questions: [
            { q: "166. Method of delivering the message is known as _____?", o: ["Reciever", "Channel", "Sender", "Feedback"], c: "Channel" },
            { q: "167. Feedback is needed in which way communication?", o: ["One-way", "Two-way", "Both 1 and 2", "None of the above"], c: "Two-way" },
            { q: "168. Communication happens when a person randomly chooses some persons to pass on the information which is of little interest but not important.", o: ["Gossip Chain", "Cluster Chain", "Probability Chain", "None of the above"], c: "Probability Chain" },
            { q: "169. The communication starts when a person tells something to a group of people, and then they pass on the information to some more people and in this way the information is passed on to everyone.", o: ["Gossip Chain", "Probability Chain", "Either 1 or 2", "None of the above"], c: "Gossip Chain" },
            { q: "170. Which of the following is not an advantage of formal communication?", o: ["Reliable", "Fast", "Secrecy", "None of the above"], c: "Secrecy" },
            { q: "171. At which stage the communicator focuses on correcting the grammar, spellings and punctuations.", o: ["Proof Reading", "Revising and editing", "Either 1 or 2", "None of the above"], c: "Proof Reading" },
            { q: "172. Study of body language of a person is called", o: ["Kinesics", "Chronemics", "Paralanguage", "None of the above"], c: "Kinesics" },
            { q: "173. A cloud computing is availability of computer resources?", o: ["Off demand", "From demand", "On demand", "None of the above"], c: "On demand" },
            { q: "174. The cost incurred in interacting with customers via video call has been _____?", o: ["Constant", "Reduced", "Increased", "None of the above"], c: "Increased" },
            { q: "175. Providing Frequently Asked Questions (FAQs) to customers result in which of the following benefits of internet communication?", o: ["Support care", "Professional presentation", "Personal touch", "None of the above"], c: "Support care" },
            { q: "176. Professional behaviour includes behave in a _____ manner in the workplace?", o: ["Neutral", "Positive", "Negative", "None of the above"], c: "Positive" },
            { q: "177. Business attire refers to _____ in a professional conduct?", o: ["Manners", "Qualities", "Clothing", "None of the above"], c: "Clothing" },
            { q: "178. It is _____ to interrupt people while they are speaking?", o: ["Polite", "Desirable", "Rude", "None of the above"], c: "Rude" },
            { q: "179. At the end of the day, who needs to be satisfied?", o: ["Company", "Customers", "Suppliers", "None of the above"], c: "Customers" },
            { q: "180. Writing is _____ in nature?", o: ["Personal", "Impersonal", "Neutral", "None of the above"], c: "Personal" }
        ]
    },
    {
        setName: "Set 13",
        questions: [
            { q: "181. Which of the following skills is the most important for professionals like editors?", o: ["Oral skills", "Writing Skills", "Presenting skills", "None of the above"], c: "Writing Skills" },
            { q: "182. In which type of letter, buyers want to know the price and quality of the goods they are willing to buy?", o: ["Quotation", "Enquiry", "Complaint", "Order"], c: "Enquiry" },
            { q: "183. How many reports are there on the basis of legality?", o: ["2", "3", "1", "None of the above"], c: "2" },
            { q: "184. A stage wherein member have spotted the differences in their cultures and they look upon these differences as negatives is called", o: ["Minimization", "Integration", "Denial", "None of the above"], c: "None of the above" },
            { q: "185. Mr. A and Mr. B belong to two distinct cultural backgrounds. Mr. B believes that his culture is superior compared to the culture of Mr. A. This phenomenon is known as", o: ["Defence", "Ethnocentrism", "Denial", "None of the above"], c: "Ethnocentrism" },
            { q: "186. _____ stage at which members learn to accept each other's culture however they still remain devoted to their own respective cultures", o: ["Adoption", "Integration", "Denial", "Minimization"], c: "Adoption" },
            { q: "187. Recognizing the different types of cultures, the similarities and differences between them without being judgemental is called", o: ["Acceptance", "Cultural Sensitivity", "Adoption", "Integration"], c: "Cultural Sensitivity" },
            { q: "188. Which of the following is not an example of a physical communication barrier?", o: ["Telephonic Disturbances", "Distance", "Background noises", "Language"], c: "Language" },
            { q: "189. Excessive usage of technical jargons and double meaning words are what type of barrier?", o: ["Sematic Barriers", "Psychological Barriers", "Physical Barriers", "None of the above"], c: "Sematic Barriers" },
            { q: "190. Information Overload is when", o: ["Listener gets inadequate information", "Listener gets too much information", "Listener gets adequate information", "Listener is inattentive"], c: "Listener gets too much information" },
            { q: "191. What is the process called where disputes are settled without the intervention of a judicial institution or trial?", o: ["Judicial Review", "Alternative Dispute Resolution (ADR)", "Legal Arbitration", "Civil Litigation"], c: "Alternative Dispute Resolution (ADR)" },
            { q: "192. Which types of matters can ADR help resolve?", o: ["Only criminal cases", "Only civil and industrial matters", "Civil, commercial, industrial, and family matters.", "Only family disputes"], c: "Civil, commercial, industrial, and family matters." },
            { q: "193. What is the decision made by the arbitral tribunal called?", o: ["Verdict", "Decree", "Award", "Order"], c: "Award" },
            { q: "194. What is the role of the conciliator in conciliation?", o: ["To assist the parties in reaching a mutually satisfactory settlement", "To issue a judgment", "To enforce the law", "To represent one party"], c: "To assist the parties in reaching a mutually satisfactory settlement" },
            { q: "195. Who helps the parties reach a resolution in mediation?", o: ["Judge", "Arbitrator", "Lawyer", "Mediator"], c: "Mediator" }
        ]
    },
    {
        setName: "Set 14",
        questions: [
            { q: "196. What is the role of the mediator in a dispute?", o: ["To give a final decision", "To enforce the law", "To help the parties communicate and settle the dispute themselves", "To represent one party in court"], c: "To help the parties communicate and settle the dispute themselves" },
            { q: "197. What is Lok Adalat also known as?", o: ["Civil Court", "High Court", "Public Tribunal", "People's Court"], c: "People's Court" },
            { q: "198. Can the order of a Lok Adalat be appealed in a court of law?", o: ["Yes, within 30 days", "Yes, with special permission", "No, it is not appealable", "Only in the Supreme Court"], c: "No, it is not appealable" },
            { q: "199. Who can issue ordinances when Parliament or State Legislature is not in session?", o: ["Prime Minister and Chief Ministers", "Speaker of the House and Governors", "President and Governors", "Election Commission"], c: "President and Governors" },
            { q: "200. What type of jurisdiction allows the Supreme Court to hear appeals against any order of the High Court?", o: ["Original Jurisdiction", "Appellate Jurisdiction", "Advisory Jurisdiction", "Special Jurisdiction"], c: "Appellate Jurisdiction" },
            { q: "201. Will all agreements give rise to a contract?", o: ["Yes, always", "No, only if there is a legal obligation", "Only social agreements become contracts", "All oral agreements are contracts"], c: "No, only if there is a legal obligation" },
            { q: "202. What must an agreement give rise to in order to become a contract?", o: ["Legal obligation", "Financial loss", "Verbal consent", "Written record"], c: "Legal obligation" },
            { q: "203. When is an agreement regarded as a contract?", o: ["When it is written down", "When it is signed by a lawyer", "When it is enforceable by law", "When both parties verbally agree"], c: "When it is enforceable by law" },
            { q: "204. According to Section 2(d), what is 'consideration' in a contract?", o: ["A written contract", "Something done or promised to be done at the desire of the promisor", "Mutual friendship", "A legal punishment"], c: "Something done or promised to be done at the desire of the promisor" },
            { q: "205. What transforms an agreement into a contract?", o: ["Presence of a witness", "Verbal communication", "Enforceability by law", "Registration in court"], c: "Enforceability by law" },
            { q: "206. In the agreement where A promises to sell his house to B for 5,00,000, who is the promisor?", o: ["A", "B", "The broker", "The registrar"], c: "A" },
            { q: "207. What is the definition of a proposal (offer) under the Indian Contract Act?", o: ["A mutual discussion between two parties", "A legal document prepared by a lawyer", "A person's willingness to do or abstain from doing something to obtain the assent of another", "A statement of intent with no expectation of acceptance"], c: "A person's willingness to do or abstain from doing something to obtain the assent of another" },
            { q: "208. In a voidable contract, who has the right to enforce or reject the contract?", o: ["The court", "Both parties equally", "None of the parties", "One or more of the parties to the contract"], c: "One or more of the parties to the contract" },
            { q: "209. According to Section 14 of the Indian Contract Act, consent is said to be free when it is not caused by:", o: ["Free will", "Legal advice", "Coercion, undue influence, fraud, misrepresentation or mistake", "Written agreement"], c: "Coercion, undue influence, fraud, misrepresentation or mistake" },
            { q: "210. Who is considered a competent party under the Indian Contract Act?", o: ["A person aged 16 with consent", "A person 18 years old, of sound mind, and not disqualified by law", "A mentally unstable person", "A foreign national without legal identity"], c: "A person 18 years old, of sound mind, and not disqualified by law" }
        ]
    },
    {
        setName: "Set 15",
        questions: [
            { q: "211. An agreement which is not enforceable by law and has no legal consequences is called:", o: ["Voidable Agreement", "Void Agreement", "Valid Contract", "Contingent Contract"], c: "Void Agreement" },
            { q: "212. A has two bikes a Hero Honda and a Bajaj Pulsar. He offers to sell his Pulsar, but does not mention which bike he is selling, B, thinking A is offering to sell his Hero Honda, accepts the offer. Based on this situation, why is there no valid agreement between A and B?", o: ["Because A did not specify a price", "Because B did not pay any advance", "Because there was no consensus ad idem (meeting of minds)", "Because both bikes are of different makes"], c: "Because there was no consensus ad idem (meeting of minds)" },
            { q: "213. What happens if there is no consensus ad idem between the parties?", o: ["The contract becomes voidable", "There cannot be any contract at all", "The contract becomes illegal", "The contract is enforceable but with penalties"], c: "There cannot be any contract at all" },
            { q: "214. Anil puts three one-rupee coins into a platform ticket vending machine at the railway station. As soon as he does this, a valid contract is formed. What does Anil's act represent?", o: ["A counteroffer", "A rejection of offer", "A mere invitation to offer", "An acceptance of an implied offer"], c: "An acceptance of an implied offer" },
            { q: "215. A father and daughter agree to go for a morning walk every day. This agreement is not a valid contract. Why?", o: ["Because it lacks consideration", "Because it is not in writing", "Because it involves a minor", "Because it is a social agreement, not intended to create legal relations"], c: "Because it is a social agreement, not intended to create legal relations" },
            { q: "216. In the case where a father and daughter agree to go for a morning walk daily, which essential element of a valid contract is missing?", o: ["Intention to create legal relationship", "Offer and acceptance", "Free consent", "Lawful consideration"], c: "Intention to create legal relationship" },
            { q: "217. The agreement between a father and daughter to go on a morning walk is best described as:", o: ["A valid contract", "A void contract", "A social agreement", "A voidable contract"], c: "A social agreement" },
            { q: "218. Ramamurthy, who is a citizen of India, enters into an agreement with his alien friend. The agreement is said to be a valid contract. Why is this so?", o: ["Because a contract between a citizen and an alien friend is not prohibited by law", "Because only citizens can form valid contracts", "Because aliens have no contractual rights in India", "Because the contract involves social relations"], c: "Because a contract between a citizen and an alien friend is not prohibited by law" },
            { q: "219. A contracts with B, a local criminal, to beat his business competitor. This act is forbidden by law. What is the legal status of this agreement?", o: ["It is a valid contract", "It is a voidable contract", "It is a void contract", "It is an illegal and unenforceable contract"], c: "It is an illegal and unenforceable contract" },
            { q: "220. A enters into an agreement with B, a local criminal, to physically harm his business rival. Which essential element of a valid contract is missing here?", o: ["Free consent", "Lawful consideration and lawful object", "Competency of parties", "Offer and acceptance"], c: "Lawful consideration and lawful object" },
            { q: "221. When a person withdraws cash from an ATM, no words are spoken between the person and the bank, but a contract is formed. What type of contract is this?", o: ["Express contract", "Implied contract", "Tacit contract", "Void contract"], c: "Tacit contract" },
            { q: "222. In which of the following situations does a tacit contract arise?", o: ["Two people signing a written agreement", "One person makes an oral promise to another", "A buyer places the highest bid, and the hammer falls at an auction sale", "A contract is made before a notary public"], c: "A buyer places the highest bid, and the hammer falls at an auction sale" },
            { q: "223. Ajit sees a book displayed on a shelf in a bookshop with a price tag of ₹95. He offers 95 at the counter and asks for the book. The bookseller refuses, saying the book has already been sold. What is the correct legal position?", o: ["The bookseller must sell the book to Ajit", "The display of the book with a price tag is an offer, and Ajit's payment is acceptance", "The display of the book is only an invitation to offer, not a legal offer", "The contract is completed when Ajit picks up the book"], c: "The display of the book is only an invitation to offer, not a legal offer" },
            { q: "224. According to Section 25, what is the general rule regarding agreements made without consideration?", o: ["They are valid", "They are void", "They are partially valid", "They require judicial approval"], c: "They are void" },
            { q: "225. Which of the following is an exception to the rule that an agreement without consideration is void?", o: ["Promise made to pay a debt barred by law", "Promise made for illegal activities", "Promise made without any written form", "Promise made between strangers"], c: "Promise made to pay a debt barred by law" }
        ]
    },
    {
        setName: "Set 16",
        questions: [
            { q: "226. Under Section 25(1), an agreement made without consideration is valid if it is:", o: ["Made verbally", "Made on account of natural love and affection", "Made for commercial purposes", "Made only between business partners"], c: "Made on account of natural love and affection" },
            { q: "227. What happens to a gift once it is completed, even if there was no consideration?", o: ["It can be revoked by the giver", "It cannot be recovered on the ground of absence of consideration", "It becomes invalid automatically", "It requires mutual consent to remain valid"], c: "It cannot be recovered on the ground of absence of consideration" },
            { q: "228. What does 'remission' in contract law mean?", o: ["Complete cancellation of the contract", "Lesser performance of the contract than originally agreed", "Changing the terms of the contract", "Performance of a contract by a third party"], c: "Lesser performance of the contract than originally agreed" },
            { q: "229. If a party agrees to perform less than originally promised under a contract, this is called:", o: ["Novation", "Rescission", "Remission", "Counter Offer"], c: "Remission" },
            { q: "230. Can an insolvent person enter into a contract relating to his property?", o: ["Yes, at any time", "No, not while insolvency proceedings are ongoing", "Only with creditor's permission", "Only if the contract benefits the creditors"], c: "No, not while insolvency proceedings are ongoing" },
            { q: "231. Can a drunken or intoxicated person enter into a valid contract?", o: ["No, while intoxication lasts and they are incapable of understanding the contract", "Yes, at any time", "Only if the contract is witnessed", "Yes, if they sign in writing"], c: "No, while intoxication lasts and they are incapable of understanding the contract" },
            { q: "232. A contract is not voidable because it was caused by a mistake as to any law in force in India; but mistake as to a law not in force in India has the same effect as:", o: ["A mistake of case", "A mistake of fact", "A mistake of law", "A mistake of understanding"], c: "A mistake of fact" },
            { q: "233. Which of the following contracts by a company may be invalid?", o: ["Contracts made within its business scope", "Contracts outside the Memorandum of Association", "Contracts for daily operations", "Contracts signed by the CEO"], c: "Contracts outside the Memorandum of Association" },
            { q: "234. In contracts involving personal skill or ability, what happens upon the death of the person?", o: ["The contract continues through legal representatives", "The contract is transferred to the employer", "The contract is terminated", "The performance is postponed"], c: "The contract is terminated" },
            { q: "235. What does unauthorized material alteration in a contract lead to?", o: ["Discharge of the contract", "Renewal of the contract", "Amendment of the contract automatically", "No effect on the contract"], c: "Discharge of the contract" },
            { q: "236. when a part-time lecturer becomes a full-time lecturer, the earlier contract is discharged by:", o: ["Breach", "Performance", "Agreement", "Merger"], c: "Merger" },
            { q: "237. if A and B plan to marry but A goes mad before the marriage, the contract becomes:", o: ["Valid", "Void due to impossibility of performance", "Illegal", "Conditional"], c: "Void due to impossibility of performance" },
            { q: "238. The term 'Quantum Meruit' literally means:", o: ["Payment in advance", "As much as is merited or earned", "As per the contract terms", "Payment after completion only"], c: "As much as is merited or earned" },
            { q: "239. What are E-contracts?", o: ["Contracts written and signed on paper", "Contracts that are not paper-based and are electronic in nature", "Verbal agreements made in person", "Contracts that require physical presence of parties"], c: "Contracts that are not paper-based and are electronic in nature" },
            { q: "240. What is another name for Actual Breach of Contract?", o: ["Future breach", "Present breach", "Conditional breach", "Partial breach"], c: "Present breach" }
        ]
    },
    {
        setName: "Set 17",
        questions: [
            { q: "241. Where the trees were sold so that they were to be cut out and separated from land and taken away by the buyer. This sale is considered a sale of:", o: ["Immovable property", "Future goods only", "Goods as movable property", "Services, not goods"], c: "Goods as movable property" },
            { q: "242. What are specific goods?", o: ["Goods that are not yet manufactured", "Goods identified and agreed upon at the time the contract of sale is made", "Goods sold in bulk without identification", "Goods that are intangible"], c: "Goods identified and agreed upon at the time the contract of sale is made" },
            { q: "243. In a contract of sale, when one table is sold out of 25 tables, under which condition would the table be considered specific goods?", o: ["If the table is manufactured after the contract", "If the table is not separated from the rest", "If the table is delivered after payment", "If the table is selected before the contract of sale is made"], c: "If the table is selected before the contract of sale is made" },
            { q: "244. When the buyer does not select goods for him from a lot but the goods are defined only by description, they are called:", o: ["Specific goods", "Contingent goods", "Unascertained goods", "Future goods"], c: "Unascertained goods" },
            { q: "245. where ABC agrees to sell to XYZ all the apples which will be produced in his garden next year, these apples are classified as:", o: ["Future goods", "Unascertained goods", "Specific goods", "Contingent goods"], c: "Future goods" },
            { q: "246. X selected some party wears in a retail showroom, agreed to take delivery next day and pay next week, but the party wears are destroyed by fire the same day, who bears the loss?", o: ["The seller, because goods were not delivered", "The insurance company only", "No one, as the contract is void", "The buyer, because property in goods had passed to him"], c: "The buyer, because property in goods had passed to him" },
            { q: "247. A sends 3 dozen silk saris to B on approval or sale or return basis with an option to return within 21 days. B sends a letter of approval within 15 days. When does the sale take place?", o: ["On the day B sends the letter of approval", "On the day the goods were sent", "On the 21st day automatically", "Only after payment is made"], c: "On the day B sends the letter of approval" },
            { q: "248. B of Benaras writes to C of Chennai to send 50 wrist watches by parcel post. C sends the parcel with the correct address, but it is misplaced and never reaches B. Who bears the loss?", o: ["C, the seller", "B, the buyer", "The post office", "Both B and C equally"], c: "B, the buyer" },
            { q: "249. A wants to sell his typewriter and tells B, who has not seen it, that it is a brand new machine. B agrees to buy it. On delivery, the machine is found to be old and repaired. What right does B have?", o: ["B must accept the machine", "B can repudiate the contract and return the machine", "B has no claim", "B can only pay half the price"], c: "B can repudiate the contract and return the machine" },
            { q: "250. What does the warranty of freedom from encumbrances imply?", o: ["The goods are of merchantable quality.", "The goods are free from any charge or claim by a third party.", "The goods match the sample provided.", "The goods will be delivered on time."], c: "The goods are free from any charge or claim by a third party." },
            { q: "251. Which of the following is an example of actual delivery?", o: ["The seller gives the car keys to the buyer, but the car remains in the seller's garage.", "The buyer receives an invoice but not the goods.", "The seller hands over a car to the buyer directly.", "The seller ships the car via courier without the buyer's acknowledgement."], c: "The seller hands over a car to the buyer directly." },
            { q: "252. What right does Section 41 of the Sale of Goods Act give to the buyer?", o: ["Right to reject goods without examining them", "Right to examine goods delivered to him which he has not previously examined", "Right to claim damages immediately after delivery", "Right to resell the goods before payment"], c: "Right to examine goods delivered to him which he has not previously examined" },
            { q: "253. How can a negotiable instrument be transferred?", o: ["Only by delivery", "Only by endorsement", "By delivery or by endorsement and delivery", "By sale in the market"], c: "By delivery or by endorsement and delivery" },
            { q: "254. What does 'ad infinitum transfer' of a negotiable instrument mean?", o: ["It can be transferred only once", "It expires if transferred more than twice", "It cannot be transferred", "It can be transferred any number of times until its maturity"], c: "It can be transferred any number of times until its maturity" },
            { q: "255. A bill drawn, accepted, or endorsed without consideration is known as:", o: ["Genuine bill", "Fictitious bill", "Accommodation bill", "Bearer bill"], c: "Accommodation bill" }
        ]
    },
    {
        setName: "Set 18",
        questions: [
            { q: "256. Which of the following is essential for a general crossing of a cheque?", o: ["Two parallel transverse lines", "The words 'Not negotiable'", "The drawer's signature", "The date of the cheque"], c: "Two parallel transverse lines" },
            { q: "257. A cheque is said to be specially crossed when:", o: ["It bears two parallel transverse lines only", "It is signed by the drawer", "It is payable to bearer", "It bears the addition of the name of a banker across its face, with or without the words 'Not Negotiable'"], c: "It bears the addition of the name of a banker across its face, with or without the words 'Not Negotiable'" },
            { q: "258. Which of the following is true regarding special crossing?", o: ["It is the same as general crossing", "It restricts the payment of the cheque to a particular banker", "It allows payment to any person presenting the cheque", "It makes the cheque dishonorable automatically"], c: "It restricts the payment of the cheque to a particular banker" },
            { q: "259. Who is allowed to perform a double crossing?", o: ["Only the banker to whom the cheque is initially crossed", "Any private party presenting the cheque", "The drawer of the cheque", "The holder in due course"], c: "Only the banker to whom the cheque is initially crossed" },
            { q: "260. A cheque is dishonoured when:", o: ["It is paid to the payee", "The drawer cancels it before payment", "The bank refuses to pay the amount to the payee", "It is crossed generally"], c: "The bank refuses to pay the amount to the payee" },
            { q: "261. The Cheque Return Memo contains:", o: ["The signature of the drawer", "Instructions for double crossing", "Bank's profit details", "Reasons for the dishonour of the cheque"], c: "Reasons for the dishonour of the cheque" },
            { q: "262. How does crossing a cheque help prevent fraud?", o: ["It allows the cheque to be paid to anyone", "It makes the cheque non-negotiable", "Misuse can be easily traced and the fraudulent person detected", "It guarantees the drawer's signature"], c: "Misuse can be easily traced and the fraudulent person detected" },
            { q: "263. Which of the following is a condition for a payment to be considered 'in due course'?", o: ["It must be made to the person in possession of the instrument and entitled to payment", "It can be made to any person, regardless of possession", "It can be in any form, including barter", "It must be made before the maturity date"], c: "It must be made to the person in possession of the instrument and entitled to payment" },
            { q: "264. When does truncation of a cheque occur?", o: ["After dishonour by the drawee bank", "Only when the cheque is lost", "After payment in cash across the counter", "Immediately on generation of an electronic image during the clearing cycle"], c: "Immediately on generation of an electronic image during the clearing cycle" },
            { q: "265. To whom is the payment in a promissory note made?", o: ["Only to the maker", "To a certain person, to the order of that person, or to the bearer of the instrument", "Only to the drawer", "To any person presenting it"], c: "To a certain person, to the order of that person, or to the bearer of the instrument" },
            { q: "266. The promise to pay in a promissory note must be:", o: ["Conditional on the payee's acceptance", "Unconditional and express", "Payable in goods or services", "Only to a bank"], c: "Unconditional and express" },
            { q: "267. An instrument that is incomplete in some respect is called:", o: ["Promissory Note", "Escrow Instrument", "Inchoate Instrument", "Truncated Cheque"], c: "Inchoate Instrument" },
            { q: "268. An Escrow Instrument is:", o: ["An instrument payable immediately in cash", "An instrument drawn conditionally or for a special purpose, not for transferring property", "Always a promissory note", "A cheque that is dishonoured"], c: "An instrument drawn conditionally or for a special purpose, not for transferring property" },
            { q: "269. A bill of exchange without any documents relating to goods attached is called:", o: ["Clean bill", "Documentary bill", "Inchoate instrument", "Escrow instrument"], c: "Clean bill" },
            { q: "270. What is the primary purpose of a product disclaimer?", o: ["To warn buyers about any harmful side effects or dangers of the product", "To promote the product's features", "To advertise the product legally", "To negotiate prices with buyers"], c: "To warn buyers about any harmful side effects or dangers of the product" }
        ]
    },
    {
        setName: "Set 19",
        questions: [
            { q: "271. Which form of written communication presents the actual financial status of a company?", o: ["Product disclaimers", "Financial reporting", "Marketing communications", "Internal communications"], c: "Financial reporting" },
            { q: "272. In marketing communications, what must the salesperson be careful about?", o: ["Using technical jargon", "Being tactful and clever in word usage to avoid violating business communication laws", "Speaking loudly", "Avoiding all communication with customers"], c: "Being tactful and clever in word usage to avoid violating business communication laws" },
            { q: "273. Why is it important to avoid beating around the bush in communication?", o: ["To confuse the listener", "To keep the message precise and clear", "To make the conversation longer", "To impress the listener"], c: "To keep the message precise and clear" },
            { q: "274. Why is feedback important in business communication?", o: ["To confuse the stakeholders", "To delay decision-making", "To reduce communication", "To ensure the listener understood the message as intended"], c: "To ensure the listener understood the message as intended" },
            { q: "275. How does proper division of labor help organizational communication?", o: ["It increases workload on employees", "It reduces information overload and delays in communication", "It complicates communication channels.", "It isolates departments"], c: "It reduces information overload and delays in communication" },
            { q: "276. Physical barriers in communication are mainly created due to:", o: ["Differences in opinions", "Emotional conflicts", "Lack of vocabulary", "Disturbances in the surroundings or environment"], c: "Disturbances in the surroundings or environment" },
            { q: "277. Who proposed the six stages of Intercultural Sensitivity?", o: ["Milton Bennett", "Abraham Maslow", "Peter Drucker", "Edward T. Hall"], c: "Milton Bennett" },
            { q: "278. During the Denial stage, what is the main challenge faced by members?", o: ["Over-acceptance of other cultures", "Adapting too quickly to new cultures", "Ignoring the existence of cultural differences", "Being judgmental about others values"], c: "Ignoring the existence of cultural differences" },
            { q: "279. In which stage do members view the differences in culture as negative and believe their own culture is superior?", o: ["Minimization", "Denial", "Defence", "Acceptance"], c: "Defence" },
            { q: "280. Advertising through newspapers, magazines, and brochures is called:", o: ["Broadcast Advertising", "Outdoor Advertising", "Print Media Advertising", "Digital Advertising"], c: "Print Media Advertising" },
            { q: "281. Which type of report presents only facts about an activity without any note or suggestions?", o: ["Analytical Report", "Research Report", "Information Report", "Special Report"], c: "Information Report" },
            { q: "282. Reports that are based on research conducted on a particular problem are known as:", o: ["Information Reports", "Research Reports", "Routine Reports", "Statutory Reports"], c: "Research Reports" },
            { q: "283. Which of the following is considered good telephone etiquette?", o: ["Calling clients at odd hours", "Using warm greetings like 'Good morning' and 'Thank you'", "Giving long, unstructured explanations", "Interrupting the client frequently"], c: "Using warm greetings like 'Good morning' and 'Thank you'" },
            { q: "284. A seller sends a letter providing details about price, quality, and terms of sale after receiving an enquiry. This is known as:", o: ["Complaint Letter", "Recovery Letter", "Quotation Letter", "Order Letter"], c: "Quotation Letter" },
            { q: "285. One of the primary reasons businesses write and draft messages is to:", o: ["Entertain their employees", "Inform, persuade, and create goodwill", "Confuse competitors", "Delay decision-making"], c: "Inform, persuade, and create goodwill" }
        ]
    },
    {
        setName: "Set 20",
        questions: [
            { q: "286. Building trust among stakeholders and developing company reputation is mainly part of:", o: ["Informing", "Persuading", "Creating Goodwill", "Reporting"], c: "Creating Goodwill" },
            { q: "287. Effective communication with customers helps a business by:", o: ["Reducing customer satisfaction", "Damaging business reputation", "Enhancing customer satisfaction and reputation", "Ignoring customer needs"], c: "Enhancing customer satisfaction and reputation" },
            { q: "288. Courteous communication helps in:", o: ["Showing superiority of one team over another", "Maintaining healthy working relationships", "Ignoring others' opinions", "Using harsh and direct language"], c: "Maintaining healthy working relationships" },
            { q: "289. What is essential for the speaker to avoid miscommunication?", o: ["Speaking rapidly and emotionally", "Delivering the message in a concrete and clear manner", "Using technical jargon", "Avoiding examples"], c: "Delivering the message in a concrete and clear manner" },
            { q: "290. A debate is usually based on:", o: ["Current affairs or specific situations", "Imaginative storytelling", "Poetry and creative writing", "Historical speeches"], c: "Current affairs or specific situations" }
        ]
    }
];