// --- DATA: Full MCQ Bank Extracted from 10.txt ---
const quizSets = [
    {
        setName: "Set 1",
        questions: [
            { q: "Which of the following is/are not characteristic of a company?", o: ["It is a distinct legal entity existing independent of its members.", "It has a perpetual succession.", "The shares of a company are freely transferable except in case of a Private limited Company.", "It is a voluntary association of persons usually for social upliftment without expectation of any profit."], c: "It is a voluntary association of persons usually for social upliftment without expectation of any profit." },
            { q: "Which of the following is/are the important feature/s of a company?", o: ["Accounting process is highly regulated and guided by regulatory pronouncements", "Constituents of periodical accounts (i.e., income statement, balance sheet etc.) are specified by the law", "Importance of compliance to the prescribed rules and regulations is paramount", "All of these"], c: "All of these" },
            { q: "In India, accounting in of a company form is guided by which of the following regulatory sources?", o: ["Companies Act, 2013", "Company Rules", "Accounting Standards", "All of these"], c: "All of these" },
            { q: "Which of the following is not a statutory book of a company?", o: ["Register of Investments held and their names", "Annual returns", "Register of Officers", "Register of shareholdings of the directors"], c: "Register of Officers" },
            { q: "Which of the following is/are not a feature/s of Shares have the following features?", o: ["It represents the biggest share in the company's equity", "It is an interest in the company, having a right to receive a share of the profit", "Shares are movable property", "It represents an individual's total ownership of the company"], c: "It represents an individual's total ownership of the company" },
            { q: "Equity shares of a company are:", o: ["A part of its debt capital", "A part of its preference capital", "A part of its ownership capital", "A type of loan from shareholders"], c: "A part of its ownership capital" },
            { q: "Which of the following is true for Preference shares?", o: ["Preference shares carry a fixed rate of dividend", "Preference shares have a right to receive dividend before equity shares", "Preference shares have a right to receive capital before equity shares in case of winding up", "All of the above"], c: "All of the above" },
            { q: "When shares are issued at a price higher than their face value, it is called:", o: ["Issue at Par", "Issue at Discount", "Issue at Premium", "Issue at Market Value"], c: "Issue at Premium" },
            { q: "The maximum rate of discount at which shares can be issued as per Companies Act, 2013 is:", o: ["5%", "10%", "Shares cannot be issued at discount (except sweat equity)", "No limit"], c: "Shares cannot be issued at discount (except sweat equity)" },
            { q: "Forfeiture of shares results in the reduction of:", o: ["Authorised Capital", "Issued Capital", "Paid-up Capital", "Reserve Capital"], c: "Paid-up Capital" },
            { q: "The balance in the 'Forfeited Shares Account' is shown in the Balance Sheet under the head:", o: ["Reserves and Surplus", "Share Capital", "Current Liabilities", "Non-Current Liabilities"], c: "Share Capital" },
            { q: "After re-issue of forfeited shares, the balance in 'Forfeited Shares Account' is transferred to:", o: ["General Reserve", "Capital Reserve", "Profit and Loss Account", "Securities Premium"], c: "Capital Reserve" },
            { q: "A company can issue Global Depository Receipts (GDRs) as per Section:", o: ["Section 41", "Section 52", "Section 62", "Section 71"], c: "Section 41" },
            { q: "The process of cancelling the existing shares and issuing new shares in their place is known as:", o: ["Bonus issue", "Rights issue", "Buyback of shares", "Capital reduction"], c: "Capital reduction" },
            { q: "Which of the following cannot be used for the issue of Bonus Shares?", o: ["Securities Premium Account", "Capital Redemption Reserve Account", "Revaluation Reserve", "Free Reserves"], c: "Revaluation Reserve" },
            { q: "Rights shares are issued to:", o: ["Public", "Existing employees", "Existing shareholders", "Institutional investors"], c: "Existing shareholders" },
            { q: "Buyback of shares must be completed within ___ from the date of passing the special resolution.", o: ["6 months", "12 months", "18 months", "24 months"], c: "12 months" },
            { q: "Debentures represent the:", o: ["Ownership capital of the company", "Loan capital of the company", "Preference capital", "Short term credit"], c: "Loan capital of the company" },
            { q: "Premium on redemption of debentures is a:", o: ["Personal Account", "Real Account", "Nominal Account", "Representative Personal Account"], c: "Representative Personal Account" },
            { q: "DRR stands for:", o: ["Debenture Recovery Rate", "Debenture Redemption Reserve", "Dividend Redemption Rate", "None of the above"], c: "Debenture Redemption Reserve" },
            { q: "A company must create DRR equivalent to at least ___% of the value of debentures to be redeemed (subject to exceptions).", o: ["10%", "25%", "50%", "100%"], c: "10%" },
            { q: "Underwriting of shares means:", o: ["Buying all shares by directors", "An agreement to take up shares if not subscribed by the public", "Registering shares with SEBI", "Issuing shares to employees"], c: "An agreement to take up shares if not subscribed by the public" },
            { q: "Maximum underwriting commission on shares as per Companies Act is:", o: ["2.5%", "5.0%", "7.5%", "10.0%"], c: "5.0%" },
            { q: "The profit earned by the company before its incorporation is called:", o: ["Revenue Profit", "Capital Profit", "Operating Profit", "Super Profit"], c: "Capital Profit" },
            { q: "Loss prior to incorporation is debited to:", o: ["Profit and Loss Account", "Goodwill Account", "Capital Reserve Account", "Preliminary Expenses"], c: "Goodwill Account" }
        ]
    },
    {
        setName: "Set 2",
        questions: [
            { q: "Divisible profits do not include:", o: ["General Reserve", "Securities Premium", "Profit and Loss credit balance", "Dividend Equalisation Reserve"], c: "Securities Premium" },
            { q: "Interim dividend is declared by:", o: ["Shareholders in AGM", "Board of Directors", "Managing Director", "Audit Committee"], c: "Board of Directors" },
            { q: "Final dividend is declared by:", o: ["Board of Directors", "Shareholders in AGM", "Company Secretary", "Government"], c: "Shareholders in AGM" },
            { q: "Cash flow statement is prepared as per:", o: ["AS 1", "AS 3", "AS 10", "AS 20"], c: "AS 3" },
            { q: "Redemption of preference shares can be done out of:", o: ["Fresh issue of shares", "Profits available for dividend", "Both A and B", "Sale of fixed assets"], c: "Both A and B" },
            { q: "CRRA (Capital Redemption Reserve Account) is created when redemption is out of:", o: ["Fresh issue", "Divisible Profits", "Securities Premium", "Capital Reserve"], c: "Divisible Profits" },
            { q: "Intrinsic value of a share is also known as:", o: ["Yield value", "Market value", "Net Asset Value", "Face value"], c: "Net Asset Value" },
            { q: "Valuation of goodwill is necessary in case of:", o: ["Amalgamation", "Sale of business", "Change in profit sharing ratio", "All of the above"], c: "All of the above" },
            { q: "Super profit is the difference between:", o: ["Average profit and Normal profit", "Gross profit and Net profit", "Net profit and Operating profit", "Actual profit and Estimated profit"], c: "Average profit and Normal profit" },
            { q: "Holding company is defined in Section:", o: ["Section 2(46)", "Section 2(87)", "Section 129", "Section 210"], c: "Section 2(46)" },
            { q: "Consolidated Financial Statements are required as per Section:", o: ["Section 129(3)", "Section 133", "Section 141", "Section 203"], c: "Section 129(3)" },
            { q: "Minority interest represents the share of:", o: ["Holding company in subsidiary", "Outside shareholders in subsidiary", "Directors in company", "Creditors in subsidiary"], c: "Outside shareholders in subsidiary" },
            { q: "Pre-acquisition profit in a subsidiary is treated by the holding company as:", o: ["Revenue Profit", "Capital Profit", "General Reserve", "Deferred Revenue"], c: "Capital Profit" },
            { q: "Post-acquisition profit in a subsidiary is treated by the holding company as:", o: ["Revenue Profit", "Capital Profit", "Capital Reserve", "Goodwill"], c: "Revenue Profit" },
            { q: "Banking companies in India are governed by:", o: ["Companies Act, 2013", "Banking Regulation Act, 1949", "Both A and B", "RBI Act only"], c: "Both A and B" },
            { q: "The 'Slip System' of posting is generally used in:", o: ["Manufacturing companies", "Electricity companies", "Banking companies", "Insurance companies"], c: "Banking companies" },
            { q: "Statutory Reserve in banks is created @ ___% of the net profit.", o: ["10%", "20%", "25%", "30%"], c: "25%" },
            { q: "Non-Performing Asset (NPA) in banks refers to an asset that ceases to generate:", o: ["Capital", "Interest", "Income", "Loss"], c: "Income" },
            { q: "Electricity companies follow:", o: ["Single Account System", "Double Account System", "Accrual System only", "Cash System"], c: "Double Account System" },
            { q: "In Double Account System, the Balance Sheet is divided into:", o: ["Capital Account and General Balance Sheet", "Income and Expenditure", "Receipts and Payments", "Fixed and Current Assets"], c: "Capital Account and General Balance Sheet" },
            { q: "Contingency Reserve in electricity companies is created out of:", o: ["Capital", "Revenue", "Loan", "Government Grant"], c: "Revenue" },
            { q: "Internal reconstruction involves:", o: ["Liquidation of company", "Reduction of share capital", "Transfer of assets to another company", "Formation of a new company"], c: "Reduction of share capital" },
            { q: "External reconstruction means:", o: ["One company goes into liquidation and a new company is formed to take over its business", "Alteration of capital only", "Compromise with creditors", "Issue of bonus shares"], c: "One company goes into liquidation and a new company is formed to take over its business" },
            { q: "Amalgamation in the nature of merger must satisfy ___ conditions as per AS 14.", o: ["3", "4", "5", "6"], c: "5" },
            { q: "In amalgamation, the company which is liquidated is called:", o: ["Transferee Company", "Transferor Company", "Vendor Company", "Both B and C"], c: "Both B and C" }
        ]
    },
    {
        setName: "Set 3",
        questions: [
            { q: "Purchase consideration is the amount payable by:", o: ["Transferor to Transferee", "Transferee to Transferor", "Shareholders to Company", "Creditors to Company"], c: "Transferee to Transferor" },
            { q: "Under the 'Purchase Method' of amalgamation, the difference between purchase consideration and net assets is treated as:", o: ["General Reserve", "Capital Reserve or Goodwill", "Profit and Loss", "Preliminary Expenses"], c: "Capital Reserve or Goodwill" },
            { q: "The main objective of Auditing is:", o: ["Detection of errors", "Detection of frauds", "Expression of opinion on financial statements", "Preparation of accounts"], c: "Expression of opinion on financial statements" },
            { q: "Auditing is a:", o: ["Continuous process", "Periodic process", "Critical examination of books of accounts", "Social service"], c: "Critical examination of books of accounts" },
            { q: "Interim audit is conducted:", o: ["At the end of the year", "Throughout the year", "Between two annual audits", "For a specific purpose"], c: "Between two annual audits" },
            { q: "Statutory audit is compulsory for:", o: ["Partnership firms", "Sole proprietorships", "All Companies", "HUF"], c: "All Companies" },
            { q: "Internal audit is appointed by:", o: ["Shareholders", "Central Government", "Management", "CAG"], c: "Management" },
            { q: "The term 'Vouching' refers to:", o: ["Physical verification of assets", "Examination of documentary evidence", "Preparation of ledger", "Checking totals"], c: "Examination of documentary evidence" },
            { q: "Internal control includes:", o: ["Internal check", "Internal audit", "Administrative control", "All of the above"], c: "All of the above" },
            { q: "Auditor of a Government Company is appointed by:", o: ["Board of Directors", "Shareholders", "Comptroller and Auditor General of India (CAG)", "Ministry of Finance"], c: "Comptroller and Auditor General of India (CAG)" },
            { q: "First auditor of a non-government company is appointed by:", o: ["Shareholders in EGM", "Board of Directors within 30 days", "Central Government", "Registrar"], c: "Board of Directors within 30 days" },
            { q: "An auditor can be removed before the expiry of his term by:", o: ["Board of Directors", "Managing Director", "Shareholders by passing a special resolution after prior approval of Central Govt.", "CAG"], c: "Shareholders by passing a special resolution after prior approval of Central Govt." },
            { q: "Section 143 of Companies Act, 2013 deals with:", o: ["Appointment of auditor", "Remuneration of auditor", "Powers and duties of auditor", "Removal of auditor"], c: "Powers and duties of auditor" },
            { q: "Audit of cost records is covered under Section:", o: ["Section 139", "Section 143", "Section 148", "Section 177"], c: "Section 148" },
            { q: "CARO 2020 stands for:", o: ["Company Audit Reform Order", "Companies (Auditor's Report) Order", "Central Audit Report Office", "None of the above"], c: "Companies (Auditor's Report) Order" },
            { q: "Audit working papers are the property of:", o: ["Client", "Auditor", "Government", "Shareholders"], c: "Auditor" },
            { q: "The standard that deals with 'Quality Control for an Audit of Financial Statements' is:", o: ["SA 200", "SA 220", "SA 300", "SA 700"], c: "SA 220" },
            { q: "Audit risk is a combination of:", o: ["Inherent risk and Control risk", "Detection risk", "Both A and B", "Business risk"], c: "Both A and B" },
            { q: "Verification of assets involves checking:", o: ["Existence", "Ownership", "Valuation", "All of the above"], c: "All of the above" },
            { q: "Qualified report is issued when:", o: ["Accounts are true and fair", "Auditor has significant disagreement with management but not pervasive", "Auditor is unable to form an opinion", "Fraud is detected"], c: "Auditor has significant disagreement with management but not pervasive" },
            { q: "Adverse report is issued when:", o: ["Accounts do not show a true and fair view", "Auditor is not independent", "Scope is restricted", "Accounts are missing"], c: "Accounts do not show a true and fair view" },
            { q: "Disclaimer of opinion is given when:", o: ["Auditor is satisfied", "Auditor is unable to obtain sufficient appropriate audit evidence", "There are minor errors", "Management is very cooperative"], c: "Auditor is unable to obtain sufficient appropriate audit evidence" },
            { q: "Which of the following is an example of an intangible asset?", o: ["Land", "Machinery", "Goodwill", "Inventory"], c: "Goodwill" },
            { q: "Current ratio is:", o: ["Current Assets / Current Liabilities", "Total Assets / Total Liabilities", "Liquid Assets / Current Liabilities", "Fixed Assets / Long term debt"], c: "Current Assets / Current Liabilities" },
            { q: "Which of the following is not a cash outflow?", o: ["Purchase of machinery", "Payment of dividend", "Depreciation", "Repayment of loan"], c: "Depreciation" }
        ]
    },
    {
        setName: "Set 4",
        questions: [
            { q: "Accounting for fixed assets is covered in:", o: ["AS 6", "AS 10", "AS 13", "AS 26"], c: "AS 10" },
            { q: "AS 20 deals with:", o: ["Consolidated Financial Statements", "Earnings Per Share", "Taxes on Income", "Intangible Assets"], c: "Earnings Per Share" },
            { q: "Segment reporting is as per:", o: ["AS 15", "AS 17", "AS 18", "AS 21"], c: "AS 17" },
            { q: "Related party disclosures are required by:", o: ["AS 1", "AS 18", "AS 24", "AS 25"], c: "AS 18" },
            { q: "Dividend is usually calculated on:", o: ["Authorised Capital", "Issued Capital", "Paid-up Capital", "Called-up Capital"], c: "Paid-up Capital" },
            { q: "Preliminary expenses are an example of:", o: ["Fixed Asset", "Current Asset", "Fictitious Asset", "Intangible Asset"], c: "Fictitious Asset" },
            { q: "The term 'Capital Reserve' refers to:", o: ["Reserve created out of revenue profits", "Reserve created out of capital profits", "Reserve for dividend", "General reserve"], c: "Reserve created out of capital profits" },
            { q: "Minimum subscription for a public issue is ___% as per SEBI.", o: ["75%", "80%", "90%", "100%"], c: "90%" },
            { q: "Sweat equity shares are issued to:", o: ["Public", "Directors/Employees for providing know-how", "Promoters for free", "Debenture holders"], c: "Directors/Employees for providing know-how" },
            { q: "Which section prohibits the issue of shares at discount?", o: ["Section 52", "Section 53", "Section 54", "Section 55"], c: "Section 53" },
            { q: "Securities premium can be used for:", o: ["Writing off preliminary expenses", "Issuing fully paid bonus shares", "Buyback of shares", "All of the above"], c: "All of the above" },
            { q: "Debentures which are transferable by mere delivery are:", o: ["Registered Debentures", "Bearer Debentures", "Secured Debentures", "Convertible Debentures"], c: "Bearer Debentures" },
            { q: "Interest on debentures is:", o: ["An appropriation of profit", "A charge against profit", "A part of dividend", "Not an expense"], c: "A charge against profit" },
            { q: "Profit on sale of an investment by a bank is shown in:", o: ["Schedule 13", "Schedule 14", "Schedule 15", "Schedule 16"], c: "Schedule 14" },
            { q: "Rebate on bills discounted is:", o: ["Accrued income", "Unearned income", "Interest expense", "Operating expense"], c: "Unearned income" },
            { q: "In the balance sheet of a bank, 'Money at call and short notice' is shown under:", o: ["Schedule 6", "Schedule 7", "Schedule 8", "Schedule 9"], c: "Schedule 7" },
            { q: "Which of the following is not a pillar of Internal Control?", o: ["Control Environment", "Risk Assessment", "Marketing Strategy", "Monitoring"], c: "Marketing Strategy" },
            { q: "Audit of a Sole Trader is:", o: ["Mandatory", "Voluntary", "Compulsory by Companies Act", "Required by SEBI"], c: "Voluntary" },
            { q: "Test checking reduces the ___ of the auditor.", o: ["Liability", "Work", "Responsibility", "Opinion"], c: "Work" },
            { q: "Management audit is:", o: ["Audit of accounts", "Audit of management functions and performance", "Audit of tax", "Statutory requirement"], c: "Audit of management functions and performance" },
            { q: "Efficiency audit ensures that:", o: ["Accounts are accurate", "Resources are used optimally to achieve targets", "Frauds are detected", "Taxes are paid"], c: "Resources are used optimally to achieve targets" },
            { q: "EDP audit relates to:", o: ["Environmental Audit", "Electronic Data Processing Audit", "Economic Audit", "None of the above"], c: "Electronic Data Processing Audit" },
            { q: "Property, Plant and Equipment (PPE) are valued at:", o: ["Cost less depreciation", "Market value", "Revalued amount", "Higher of cost or market"], c: "Cost less depreciation" },
            { q: "Accounting for government grants is as per:", o: ["AS 11", "AS 12", "AS 13", "AS 14"], c: "AS 12" },
            { q: "A 'Subsidiary' is a company in which the holding company controls more than ___ of total voting power.", o: ["One-fourth", "One-third", "One-half", "Two-thirds"], c: "One-half" }
        ]
    },
    {
        setName: "Set 5",
        questions: [
            { q: "Audit engagement letter is sent by:", o: ["Client to Auditor", "Auditor to Client", "Registrar to Auditor", "Management to Shareholders"], c: "Auditor to Client" },
            { q: "SA 500 relates to:", o: ["Audit Documentation", "Audit Evidence", "Audit Planning", "Going Concern"], c: "Audit Evidence" },
            { q: "Subsequent events are covered in:", o: ["SA 550", "SA 560", "SA 570", "SA 580"], c: "SA 560" },
            { q: "Going concern assumption is covered in:", o: ["SA 500", "SA 570", "SA 600", "SA 700"], c: "SA 570" },
            { q: "Which of the following is a specific duty of a bank auditor?", o: ["Checking cash reserves", "Verifying loan documentation", "Confirming balances with RBI", "All of the above"], c: "All of the above" },
            { q: "Inter-office adjustments in banks can be:", o: ["Assets", "Liabilities", "Either A or B", "None"], c: "Either A or B" },
            { q: "Non-performing assets are classified into:", o: ["Sub-standard assets", "Doubtful assets", "Loss assets", "All of the above"], c: "All of the above" },
            { q: "A standard asset is one which:", o: ["Does not disclose any problems", "Has interest overdue for 30 days", "Has interest overdue for 90 days", "Is fully secured"], c: "Does not disclose any problems" },
            { q: "General insurance companies prepare:", o: ["Revenue Account", "Profit and Loss Account", "Balance Sheet", "All of the above"], c: "All of the above" },
            { q: "Reserve for Unexpired Risk is maintained by:", o: ["Life Insurance companies", "General Insurance companies", "Banks", "Electricity companies"], c: "General Insurance companies" },
            { q: "Percentage of 'Reserve for Unexpired Risk' for Fire Insurance is usually:", o: ["40%", "50%", "100%", "25%"], c: "50%" },
            { q: "Percentage of 'Reserve for Unexpired Risk' for Marine Hull is:", o: ["50%", "75%", "100%", "25%"], c: "100%" },
            { q: "Commission on re-insurance accepted is:", o: ["Income", "Expense", "Liability", "Asset"], c: "Expense" },
            { q: "Commission on re-insurance ceded is:", o: ["Income", "Expense", "Liability", "Asset"], c: "Income" },
            { q: "In life insurance, 'Bonus' is given to:", o: ["Employees", "Shareholders", "Policyholders", "Directors"], c: "Policyholders" },
            { q: "Valuation Balance Sheet is prepared by:", o: ["General Insurance Co.", "Life Insurance Co.", "Banking Co.", "Holding Co."], c: "Life Insurance Co." },
            { q: "Net liability of underwriters is calculated as:", o: ["Gross liability - Marked applications", "Gross liability - Unmarked applications", "Gross liability - (Marked + Unmarked applications)", "None"], c: "Gross liability - (Marked + Unmarked applications)" },
            { q: "Marked applications are those which:", o: ["Carry the stamp of the underwriter", "Are received directly by company", "Are rejected", "Are for bonus shares"], c: "Carry the stamp of the underwriter" },
            { q: "Under the 'Net Basis' of calculating purchase consideration, we take:", o: ["Total assets - Total liabilities", "Sum of payments to shareholders", "Market value of shares", "None"], c: "Sum of payments to shareholders" },
            { q: "Under the 'Net Assets Basis', assets are taken at:", o: ["Book value", "Agreed value", "Market value", "Face value"], c: "Agreed value" },
            { q: "Intangible assets are amortized as per:", o: ["AS 10", "AS 26", "AS 28", "AS 2"], c: "AS 26" },
            { q: "AS 13 deals with:", o: ["Inventory", "Investments", "Cash flows", "Leases"], c: "AS 13" },
            { q: "Impairment of assets is covered by:", o: ["AS 26", "AS 28", "AS 10", "AS 1"], c: "AS 28" },
            { q: "Which of the following is not a source of audit evidence?", o: ["Inspection", "Observation", "Speculation", "External confirmation"], c: "Speculation" },
            { q: "The objective of an internal check is to:", o: ["Detect frauds after they happen", "Prevent errors and frauds by distribution of work", "Help management in planning", "Avoid paying taxes"], c: "Prevent errors and frauds by distribution of work" }
        ]
    },
    {
        setName: "Set 6",
        questions: [
            { q: "A 'Clean Report' is also known as:", o: ["Qualified Report", "Unqualified Report", "Adverse Report", "Disclaimer"], c: "Unqualified Report" },
            { q: "True and Fair view means:", o: ["Accounts are 100% accurate", "Accounts are prepared as per GAAP and free from material misstatements", "Auditor has checked every transaction", "None of the above"], c: "Accounts are prepared as per GAAP and free from material misstatements" },
            { q: "Social audit is concerned with:", o: ["Profit maximization", "Impact of company on society", "Audit of social clubs", "Tax compliance"], c: "Impact of company on society" },
            { q: "Environmental audit evaluates:", o: ["Financial health", "Compliance with environmental laws and impact on nature", "Employee morale", "Sales growth"], c: "Compliance with environmental laws and impact on nature" },
            { q: "Propriety audit checks:", o: ["Arithmetical accuracy", "Whether expenditure is wise and in public interest", "Compliance with rules only", "Physical assets"], c: "Whether expenditure is wise and in public interest" },
            { q: "Audit of Partnership firm is compulsory under:", o: ["Partnership Act, 1932", "Income Tax Act (if turnover exceeds limit)", "Companies Act", "SEBI"], c: "Income Tax Act (if turnover exceeds limit)" },
            { q: "The auditor should be:", o: ["Dependent on management", "Independent and objective", "A relative of the director", "A shareholder"], c: "Independent and objective" },
            { q: "In India, Accounting Standards are issued by:", o: ["SEBI", "RBI", "ICAI", "Central Government"], c: "ICAI" },
            { q: "Ind AS stands for:", o: ["Indian Accounting Standards", "International Accounting Standards", "Independent Audit Standards", "None"], c: "Indian Accounting Standards" },
            { q: "Convergence with IFRS leads to:", o: ["Ind AS", "AS", "GAAP", "IAS"], c: "Ind AS" },
            { q: "AS 1 deals with:", o: ["Disclosure of Accounting Policies", "Valuation of Inventories", "Cash Flow Statements", "Depreciation"], c: "Disclosure of Accounting Policies" },
            { q: "AS 2 deals with:", o: ["Fixed Assets", "Inventories", "Revenue Recognition", "Leases"], c: "Inventories" },
            { q: "Inventories should be valued at:", o: ["Cost price", "Net Realizable Value", "Lower of Cost or Net Realizable Value", "Market price"], c: "Lower of Cost or Net Realizable Value" },
            { q: "Revenue from sale of goods is recognized when:", o: ["Order is received", "Goods are produced", "Risk and rewards of ownership are transferred", "Cash is received"], c: "Risk and rewards of ownership are transferred" },
            { q: "AS 9 deals with:", o: ["Fixed Assets", "Revenue Recognition", "Construction Contracts", "Government Grants"], c: "Revenue Recognition" },
            { q: "Which of the following is not an item of 'Revenue' as per AS 9?", o: ["Sale of goods", "Rendering of services", "Interest, royalties and dividends", "Sale of fixed assets"], c: "Sale of fixed assets" },
            { q: "In India, which company must follow Ind AS?", o: ["All companies", "Listed companies and companies with high net worth", "Only foreign companies", "Small companies"], c: "Listed companies and companies with high net worth" },
            { q: "The first set of Ind AS was notified in:", o: ["2010", "2013", "2015", "2017"], c: "2015" },
            { q: "Which of the following is a feature of Ind AS?", o: ["Based on historical cost only", "Principle-based", "Rule-based", "Ignore fair value"], c: "Principle-based" },
            { q: "Audit of a Cooperative Society is conducted as per:", o: ["Companies Act", "Cooperative Societies Act", "Banking Act", "Income Tax Act"], c: "Cooperative Societies Act" },
            { q: "The 'Secret Reserve' can be created by:", o: ["Banks", "Insurance Companies", "Both A and B", "Manufacturing Companies"], c: "Both A and B" },
            { q: "Window dressing means:", o: ["Decorating the office", "Presenting a better financial picture than actual", "Cleaning the windows", "Preparing accurate accounts"], c: "Presenting a better financial picture than actual" },
            { q: "Which of the following is an example of an error of principle?", o: ["Omission of a transaction", "Recording a revenue expenditure as capital expenditure", "Checking the wrong total", "Posting to wrong account"], c: "Recording a revenue expenditure as capital expenditure" },
            { q: "Compensating errors are those which:", o: ["Are made intentionally", "Counterbalance each other", "Are discovered easily", "Relate to fixed assets"], c: "Counterbalance each other" },
            { q: "The 'Expectation Gap' in auditing refers to:", o: ["Gap between auditor's salary and client's expectation", "Gap between what the public expects from audit and what an audit actually provides", "Gap between two audit reports", "Time gap between audits"], c: "Gap between what the public expects from audit and what an audit actually provides" }
        ]
    },
    {
        setName: "Set 7",
        questions: [
            { q: "Auditing around the computer is used when:", o: ["IT system is complex", "IT system is simple and produces extensive printouts", "Computer is not working", "Auditor does not know computers"], c: "IT system is simple and produces extensive printouts" },
            { q: "Auditing through the computer is used for:", o: ["Manual systems", "Complex IT environments", "Small businesses", "Checking cash only"], c: "Complex IT environments" },
            { q: "CAATs stands for:", o: ["Computer Assisted Audit Techniques", "Certified Accounting Audit Tools", "Central Automated Audit Systems", "None"], c: "Computer Assisted Audit Techniques" },
            { q: "Audit of educational institutions focuses on:", o: ["Student fees", "Grants received", "Salaries paid", "All of the above"], c: "All of the above" },
            { q: "Statutory Auditor's rights include:", o: ["Right to access books", "Right to receive notice of AGM", "Right to be heard at AGM", "All of the above"], c: "All of the above" },
            { q: "If an auditor's tenure is for 5 years, he can be reappointed for:", o: ["One more term of 5 years (Individual)", "Two more terms of 5 years (Firm)", "Both A and B (as per rotation rules)", "Unlimited times"], c: "Both A and B (as per rotation rules)" },
            { q: "Which Section deals with Eligibility, Qualifications and Disqualifications of Auditors?", o: ["Section 139", "Section 140", "Section 141", "Section 142"], c: "Section 141" },
            { q: "A person who is indebted to the company for more than ___ is disqualified to be an auditor.", o: ["₹ 1,00,000", "₹ 5,00,000", "₹ 10,00,000", "₹ 50,000"], c: "₹ 5,00,000" },
            { q: "Auditor's remuneration is fixed in:", o: ["Board Meeting", "General Meeting", "Audit Committee", "Government"], c: "General Meeting" },
            { q: "Casual vacancy of an auditor (not due to resignation) is filled by:", o: ["Shareholders", "Board of Directors within 30 days", "Central Govt.", "Registrar"], c: "Board of Directors within 30 days" },
            { q: "Casual vacancy due to resignation is filled by:", o: ["Board of Directors", "Shareholders in General Meeting", "CAG", "None"], c: "Shareholders in General Meeting" },
            { q: "Ceiling limit on number of company audits for an auditor is:", o: ["10", "20", "30", "No limit"], c: "20" },
            { q: "Internal audit for certain class of companies is mandatory under Section:", o: ["Section 138", "Section 139", "Section 143", "Section 148"], c: "Section 138" },
            { q: "Secretarial Audit is applicable to:", o: ["All companies", "Public companies with certain capital/turnover", "Private companies", "HUF"], c: "Public companies with certain capital/turnover" },
            { q: "Secretarial Audit is conducted by:", o: ["Chartered Accountant", "Cost Accountant", "Company Secretary in Practice", "Advocate"], c: "Company Secretary in Practice" },
            { q: "Management is responsible for:", o: ["Preparation of financial statements", "Maintenance of internal control", "Prevention and detection of frauds", "All of the above"], c: "All of the above" },
            { q: "SA 210 deals with:", o: ["Agreeing the terms of audit engagements", "Audit documentation", "Audit planning", "Materiality"], c: "Agreeing the terms of audit engagements" },
            { q: "Audit Program is a:", o: ["Vague plan", "Detailed plan of audit procedures to be performed", "Financial budget", "List of shareholders"], c: "Detailed plan of audit procedures to be performed" },
            { q: "Materiality in planning and performing an audit is covered by:", o: ["SA 300", "SA 315", "SA 320", "SA 450"], c: "SA 320" },
            { q: "Analytical procedures are covered in:", o: ["SA 500", "SA 520", "SA 530", "SA 540"], c: "SA 520" },
            { q: "Audit sampling is covered in:", o: ["SA 500", "SA 530", "SA 560", "SA 580"], c: "SA 530" },
            { q: "Confirmation from third parties is:", o: ["Internal Evidence", "External Evidence", "Oral Evidence", "None"], c: "External Evidence" },
            { q: "Which is more reliable?", o: ["Internal Evidence", "External Evidence", "Photocopied Evidence", "Oral Evidence"], c: "External Evidence" },
            { q: "Audit of bank branches is done by:", o: ["Statutory Central Auditor", "Statutory Branch Auditor", "Internal Auditor", "RBI"], c: "Statutory Branch Auditor" },
            { q: "Long Form Audit Report (LFAR) is applicable to:", o: ["Electricity Co.", "Banking Co.", "Holding Co.", "Insurance Co."], c: "Banking Co." }
        ]
    },
    {
        setName: "Set 8",
        questions: [
            { q: "Current Assets are those which are expected to be converted into cash within:", o: ["3 months", "6 months", "12 months or normal operating cycle", "24 months"], c: "12 months or normal operating cycle" },
            { q: "Provision for bad debts is made as per the principle of:", o: ["Conservatism", "Matching", "Consistency", "Full disclosure"], c: "Conservatism" },
            { q: "Dividend unpaid for 30 days is transferred to:", o: ["General Reserve", "Capital Reserve", "Unpaid Dividend Account", "Profit and Loss"], c: "Unpaid Dividend Account" },
            { q: "Amount in 'Unpaid Dividend Account' if remains unpaid for 7 years is transferred to:", o: ["Shareholders", "Central Govt.", "Investor Education and Protection Fund (IEPF)", "Reserve Bank of India"], c: "Investor Education and Protection Fund (IEPF)" },
            { q: "A 'Company' is defined in Section:", o: ["Section 2(20)", "Section 2(11)", "Section 3", "Section 7"], c: "Section 2(20)" },
            { q: "Maximum number of members in a Private Company is:", o: ["20", "50", "100", "200"], c: "200" },
            { q: "Minimum number of members in a Public Company is:", o: ["2", "3", "7", "10"], c: "7" },
            { q: "One Person Company (OPC) can have maximum ___ director(s).", o: ["1", "5", "10", "15"], c: "15" },
            { q: "Nominal capital is also known as:", o: ["Issued Capital", "Authorised Capital", "Paid-up Capital", "Called-up Capital"], c: "Authorised Capital" },
            { q: "Underwriting commission is an example of:", o: ["Capital expenditure", "Revenue expenditure", "Deferred Revenue expenditure", "Capital receipt"], c: "Deferred Revenue expenditure" },
            { q: "A company can buy back its shares out of:", o: ["Free reserves", "Securities premium", "Proceeds of a fresh issue", "All of the above"], c: "All of the above" },
            { q: "Preference shares must be redeemed within a maximum period of ___ years (except infrastructure projects).", o: ["10 years", "15 years", "20 years", "25 years"], c: "20 years" },
            { q: "Redemption of debentures can be by:", o: ["Payment in lump sum", "Installments", "Purchase in open market", "All of the above"], c: "All of the above" },
            { q: "Profit on cancellation of own debentures is transferred to:", o: ["Profit and Loss Account", "General Reserve", "Capital Reserve", "Securities Premium"], c: "Capital Reserve" },
            { q: "The 'Ex-dividend' price of a debenture means:", o: ["Price including interest", "Price excluding interest", "Face value", "Discounted price"], c: "Price excluding interest" },
            { q: "The 'Cum-dividend' price includes:", o: ["Principal only", "Interest only", "Both principal and accrued interest", "None"], c: "Both principal and accrued interest" },
            { q: "Schedule III of Companies Act, 2013 provides the format for:", o: ["Audit Report", "Financial Statements", "Directors Report", "Memorandum"], c: "Financial Statements" },
            { q: "Part I of Schedule III deals with:", o: ["Balance Sheet", "Statement of Profit and Loss", "Cash Flow", "Notes to accounts"], c: "Balance Sheet" },
            { q: "Part II of Schedule III deals with:", o: ["Balance Sheet", "Statement of Profit and Loss", "Consolidation", "Disclosures"], c: "Statement of Profit and Loss" },
            { q: "Proposed dividend is shown as a:", o: ["Provisions", "Contingent Liability (in notes)", "Current Liability", "Reserve"], c: "Contingent Liability (in notes)" },
            { q: "Net profit as per Section 198 is used to calculate:", o: ["Tax", "Managerial remuneration", "Dividend", "Bonus"], c: "Managerial remuneration" },
            { q: "Overall managerial remuneration for a public company cannot exceed ___% of net profits.", o: ["5%", "10%", "11%", "15%"], c: "11%" },
            { q: "Managerial remuneration for a single MD cannot exceed ___% of net profits.", o: ["1%", "3%", "5%", "10%"], c: "5%" },
            { q: "Non-cash items in cash flow statement include:", o: ["Depreciation", "Provision for tax", "Profit on sale of asset", "All of the above"], c: "All of the above" },
            { q: "Cash flow from operating activities can be calculated by:", o: ["Direct method", "Indirect method", "Both A and B", "None"], c: "Both A and B" }
        ]
    },
    {
        setName: "Set 9",
        questions: [
            { q: "Interest received by a non-financial company is a:", o: ["Operating activity", "Investing activity", "Financing activity", "Cash equivalent"], c: "Investing activity" },
            { q: "Dividend paid by a company is a:", o: ["Operating activity", "Investing activity", "Financing activity", "Non-cash item"], c: "Financing activity" },
            { q: "Goodwill is tested for ___ under Ind AS.", o: ["Amortization", "Impairment", "Depreciation", "Appreciation"], c: "Impairment" },
            { q: "Goodwill should be valued on the basis of:", o: ["Past profits", "Future maintainable profits", "Assets", "Sales"], c: "Future maintainable profits" },
            { q: "Normal Rate of Return depends on:", o: ["Risk in the industry", "Bank rate", "Inflation", "All of the above"], c: "All of the above" },
            { q: "Holding company must present consolidated financial statements as per Section:", o: ["129", "133", "143", "203"], c: "129" },
            { q: "Consolidation involves adding:", o: ["Assets and Liabilities", "Incomes and Expenses", "Both A and B", "Only Profits"], c: "Both A and B" },
            { q: "Unrealized profit on inter-company stock should be:", o: ["Ignored", "Eliminated from consolidated profit and inventory", "Added to sales", "None"], c: "Eliminated from consolidated profit and inventory" },
            { q: "Inter-company debts (Debtors and Creditors) should be:", o: ["Shown separately", "Eliminated on consolidation", "Shown as contingent", "None"], c: "Eliminated on consolidation" },
            { q: "Statutory Reserve for banking companies is as per Section:", o: ["Section 17", "Section 29", "Section 30", "Section 45"], c: "Section 17" },
            { q: "Banks must maintain CRR with:", o: ["Itself", "Central Govt.", "RBI", "SBI"], c: "RBI" },
            { q: "Banks must maintain SLR with:", o: ["Itself in form of liquid assets", "RBI", "World Bank", "Stock Exchange"], c: "Itself in form of liquid assets" },
            { q: "Bills for collection is a:", o: ["Asset", "Liability", "Memorandum item", "Income"], c: "Memorandum item" },
            { q: "Acceptances, Endorsements and other obligations is shown in Schedule ___ for banks.", o: ["Schedule 9", "Schedule 10", "Schedule 11", "Schedule 12"], c: "Schedule 12" },
            { q: "A sub-standard asset is an NPA for a period less than or equal to:", o: ["6 months", "12 months", "18 months", "24 months"], c: "12 months" },
            { q: "Income on NPAs in banks is recognized on:", o: ["Accrual basis", "Cash basis", "Due basis", "None"], c: "Cash basis" },
            { q: "General Insurance business was nationalized in:", o: ["1956", "1969", "1972", "1991"], c: "1972" },
            { q: "GIC stands for:", o: ["General Information Center", "General Insurance Corporation of India", "Government Insurance Co.", "None"], c: "General Insurance Corporation of India" },
            { q: "Insurance companies are regulated by:", o: ["SEBI", "RBI", "IRDAI", "Ministry of Commerce"], c: "IRDAI" },
            { q: "Re-insurance means:", o: ["Insuring the same risk again by the policyholder", "Insurer transferring a part of risk to another insurer", "Cancelling the policy", "None"], c: "Insurer transferring a part of risk to another insurer" },
            { q: "Claims under insurance are shown in:", o: ["Revenue Account", "Profit and Loss", "Balance Sheet", "Appropriation"], c: "Revenue Account" },
            { q: "Surrender value is associated with:", o: ["Fire Insurance", "Marine Insurance", "Life Insurance", "Vehicle Insurance"], c: "Life Insurance" },
            { q: "The profit/loss on revaluation of assets at the time of internal reconstruction is transferred to:", o: ["Capital Reserve", "Capital Reduction Account", "General Reserve", "Goodwill"], c: "Capital Reduction Account" },
            { q: "When a company takes over another company and no new company is formed, it is:", o: ["Absorption", "Amalgamation", "External Reconstruction", "Internal Reconstruction"], c: "Absorption" },
            { q: "Pooling of Interest method is used in:", o: ["Amalgamation in the nature of merger", "Amalgamation in the nature of purchase", "Internal reconstruction", "Liquidation"], c: "Amalgamation in the nature of merger" }
        ]
    },
    {
        setName: "Set 10",
        questions: [
            { q: "In amalgamation, 'Goodwill' or 'Capital Reserve' arises in the books of:", o: ["Transferee Company", "Transferor Company", "Both", "None"], c: "Transferee Company" },
            { q: "AS 14 is not applicable to:", o: ["Internal Reconstruction", "Absorption", "Merger", "Purchase of business"], c: "Internal Reconstruction" },
            { q: "The document that contains the auditor's opinion is:", o: ["Audit Note Book", "Audit Working Paper", "Audit Report", "Audit Plan"], c: "Audit Report" },
            { q: "Audit of accounts of a company is:", o: ["Optional", "Mandatory", "Voluntary", "Not required"], c: "Mandatory" },
            { q: "The auditor of a company is appointed by:", o: ["The directors", "The shareholders", "The government", "The bank"], c: "The shareholders" },
            { q: "A nomination and remuneration committee should have _____ directors.", o: ["1", "2", "3", "4"], c: "3" },
            { q: "Which of the following is not an audit risk?", o: ["Control Risk", "Omission Risk", "Detection Risk", "Inherent Risk"], c: "Omission Risk" },
            { q: "Which of the following services cannot be rendered by an auditor as per Companies Act 2013?", o: ["Verification of assets and liabilities", "Vouching", "Providing investment advisory services", "Issuing certificates on relevant matters"], c: "Providing investment advisory services" },
            { q: "SA 300 stands for __________.", o: ["Audit Planning", "Responsibility of Joint Auditor", "Overall planning of audit", "None of the above"], c: "Audit Planning" },
            { q: "Ind AS 16 deals with:", o: ["Leases", "Revenue from Contracts with Customers", "Property, Plant, and Equipment", "Financial Instruments"], c: "Property, Plant, and Equipment" },
            { q: "Ind AS 38 deals with:", o: ["Revenue recognition", "Intangible assets", "Tangible assets", "Borrowing costs"], c: "Intangible assets" },
            { q: "Ind AS 33 relates to:", o: ["Earnings Per Share", "Segment Reporting", "Income Taxes", "Inventories"], c: "Earnings Per Share" },
            { q: "Ind AS 21 deals with:", o: ["The Effects of Changes in Foreign Exchange Rates", "Segment Reporting", "Income Taxes", "Earnings Per Share"], c: "The Effects of Changes in Foreign Exchange Rates" },
            { q: "The main objective of auditing is to detect errors and frauds.", o: ["True", "False", "Partially True", "None"], c: "False" },
            { q: "Statutory Auditor can be a person who is an employee of the company.", o: ["True", "False", "Only if Board agrees", "None"], c: "False" }
        ]
    }
];