// --- DATA: Full MCQ Bank Extracted from 9.txt ---
const quizSets = [
    {
        setName: "Set 1",
        questions: [
            { q: "OM deals with -", o: ["Both tangible and intangible product", "Tangible product", "Intangible services", "Tangible product and intangible services"], c: "Tangible product and intangible services" },
            { q: "One of the example of pure service:", o: ["Teaching", "Product service", "Repairing service", "All of the above"], c: "Teaching" },
            { q: "Objectives of operations management can be categorized into:", o: ["Two", "Three", "Four", "Seven"], c: "Two" },
            { q: "One of the objective of operation management is", o: ["Product service", "Customer service", "Planning", "None of them"], c: "Customer service" },
            { q: "Principal function of customer service are", o: ["Manufacture-supply-transport-service", "Manufacture-transport-service-supply", "Manufacture-service-transport-supply", "Manufacture-transport-supply-service"], c: "Manufacture-transport-supply-service" },
            { q: "The desired objective of Production and Operations Management is:", o: ["Use cheap machinery to produce", "To train unskilled workers to manufacture goods perfectly", "Optimal utilisation of available resources", "To earn good profits"], c: "Optimal utilisation of available resources" },
            { q: "Which one of the following is not an activity under productions and operations management?", o: ["Location of facilities", "Plant layouts and Material Handling", "Product Design", "Market penetration"], c: "Market penetration" },
            { q: "Operations management is concerned essentially with -", o: ["Effective utilisation of resources", "Conversion of input into output", "Creation of value", "All of the above"], c: "All of the above" },
            { q: "Operations management applies to:", o: ["Manufacturing sector", "Services sector", "Both manufacturing and service sector", "Directly to customers only"], c: "Both manufacturing and service sector" },
            { q: "The essential function of operations management is -", o: ["Planning", "Scheduling", "Controlling", "All of the above"], c: "All of the above" },
            { q: "Supply chain management (SCM) is a part of:", o: ["Marketing", "Operations management", "Human resource", "Finance"], c: "Operations management" },
            { q: "Strategic Management consists of three distinct phases. Which of the following is not a phase of strategic management?", o: ["Strategy Formulation", "Strategy Implementation", "Strategy Control", "Strategy Evaluation"], c: "Strategy Control" },
            { q: "Which of the following is the first step in the strategic management process?", o: ["Establishment of strategic intent", "Formulation of strategies", "Implementation of strategies", "Evaluation of strategies"], c: "Establishment of strategic intent" },
            { q: "Strategic Management involves -", o: ["Setting goals", "Analysing the competitive environment", "Analysing the internal organisation", "All of the above"], c: "All of the above" },
            { q: "The scope of strategic management includes:", o: ["Corporate level", "Business level", "Functional level", "All of the above"], c: "All of the above" },
            { q: "The concept of 'Strategic Intent' includes:", o: ["Vision", "Mission", "Goals and objectives", "All of the above"], c: "All of the above" },
            { q: "One of the following is a characteristic of Strategic Management:", o: ["Focuses on long-term growth", "Deals with day-to-day operations", "Is short-term in nature", "Only relates to production"], c: "Focuses on long-term growth" },
            { q: "The role of a strategist is -", o: ["To formulate strategies", "To implement strategies", "To monitor progress", "All of the above"], c: "All of the above" },
            { q: "Which of the following describes the purpose of a mission statement?", o: ["To describe the current business and why it exists", "To describe future goals", "To list daily tasks", "To identify competitors"], c: "To describe the current business and why it exists" },
            { q: "Strategy is -", o: ["A plan to achieve a goal", "A short-term tactic", "A daily operational report", "None of the above"], c: "A plan to achieve a goal" },
            { q: "The 'Triple Bottom Line' concept in strategic management refers to:", o: ["Profit, People, Planet", "Profit, Production, Promotion", "Profit, Process, Product", "Product, Price, Place"], c: "Profit, People, Planet" },
            { q: "SWOT analysis stands for:", o: ["Strengths, Weaknesses, Opportunities, Threats", "Sales, Wages, Operations, Tasks", "Strategy, Work, Objectives, Timing", "Success, Wealth, Organisation, Team"], c: "Strengths, Weaknesses, Opportunities, Threats" },
            { q: "PESTEL analysis is used to:", o: ["Analyse the external environment", "Analyse internal strengths", "Select a new product", "Evaluate employee performance"], c: "Analyse the external environment" },
            { q: "The BCG Matrix is used for:", o: ["Portfolio analysis", "SWOT analysis", "PESTEL analysis", "Supply chain management"], c: "Portfolio analysis" },
            { q: "A 'Cash Cow' in the BCG matrix represents:", o: ["High market share, low market growth", "Low market share, low market growth", "High market share, high market growth", "Low market share, high market growth"], c: "High market share, low market growth" }
        ]
    },
    {
        setName: "Set 2",
        questions: [
            { q: "In the BCG matrix, a 'Star' represents:", o: ["High market share, high market growth", "Low market share, low market growth", "High market share, low market growth", "Low market share, high market growth"], c: "High market share, high market growth" },
            { q: "A 'Dog' in the BCG matrix represents:", o: ["Low market share, low market growth", "High market share, low market growth", "High market share, high market growth", "Low market share, high market growth"], c: "Low market share, low market growth" },
            { q: "Competitive advantage refers to:", o: ["The ability to outperform competitors", "A high level of production", "A low number of employees", "High levels of debt"], c: "The ability to outperform competitors" },
            { q: "Which of the following is not one of Porter's Generic Strategies?", o: ["Cost Leadership", "Differentiation", "Focus", "Innovation"], c: "Innovation" },
            { q: "Cost Leadership strategy focuses on:", o: ["Being the lowest cost producer in the industry", "Offering unique products", "Serving a niche market", "Expanding globally"], c: "Being the lowest cost producer in the industry" },
            { q: "Differentiation strategy focuses on:", o: ["Developing unique products for which customers are willing to pay a premium", "Lowering production costs", "Serving a specific segment only", "None of the above"], c: "Developing unique products for which customers are willing to pay a premium" },
            { q: "Focus strategy involves:", o: ["Concentrating on a narrow segment of the market", "Serving all market segments", "Lowest cost production", "Mass marketing"], c: "Concentrating on a narrow segment of the market" },
            { q: "Value Chain Analysis was introduced by:", o: ["Michael Porter", "Igor Ansoff", "Philip Kotler", "Peter Drucker"], c: "Michael Porter" },
            { q: "Primary activities in a value chain include:", o: ["Inbound logistics, Operations, Outbound logistics, Marketing and Sales, Service", "Infrastructure, HR, Technology, Procurement", "Marketing, Finance, HR", "Research, Development, Testing"], c: "Inbound logistics, Operations, Outbound logistics, Marketing and Sales, Service" },
            { q: "Support activities in a value chain include:", o: ["Firm infrastructure, HR management, Technology development, Procurement", "Operations and Sales", "Logistics and Service", "Marketing and Promotion"], c: "Firm infrastructure, HR management, Technology development, Procurement" },
            { q: "Product life cycle (PLC) stages are:", o: ["Introduction, Growth, Maturity, Decline", "Planning, Production, Sales, Profit", "Design, Build, Market, Sell", "Idea, Launch, Peak, End"], c: "Introduction, Growth, Maturity, Decline" },
            { q: "Total Quality Management (TQM) is:", o: ["A management approach focused on quality in all processes", "A method for reducing wages", "A short-term project", "None of the above"], c: "A management approach focused on quality in all processes" },
            { q: "Lean Manufacturing aims to:", o: ["Minimise waste without sacrificing productivity", "Increase stock levels", "Hire more staff", "Raise prices"], c: "Minimise waste without sacrificing productivity" },
            { q: "Just-In-Time (JIT) production focuses on:", o: ["Receiving goods only as they are needed in the production process", "Maintaining high inventory", "Production in large batches", "Stockpiling raw materials"], c: "Receiving goods only as they are needed in the production process" },
            { q: "Benchmarking is:", o: ["Comparing performance against best-in-class organisations", "Setting a budget", "Increasing sales", "Reducing production"], c: "Comparing performance against best-in-class organisations" },
            { q: "Six Sigma is a technique for:", o: ["Process improvement and reducing defects", "Marketing a new product", "Financial accounting", "Calculating salaries"], c: "Process improvement and reducing defects" },
            { q: "Business Process Reengineering (BPR) involves:", o: ["Radical redesign of business processes", "Small incremental changes", "Maintaining existing structures", "Increasing bureaucracy"], c: "Radical redesign of business processes" },
            { q: "Strategic alliances are:", o: ["Agreements between two or more firms to cooperate to achieve a common goal", "Mergers", "Acquisitions", "Joint ventures only"], c: "Agreements between two or more firms to cooperate to achieve a common goal" },
            { q: "Corporate Social Responsibility (CSR) refers to:", o: ["Business commitment to contribute to sustainable economic development", "Increasing profits only", "Reducing taxes", "Marketing products"], c: "Business commitment to contribute to sustainable economic development" },
            { q: "Balanced Scorecard was developed by:", o: ["Kaplan and Norton", "Porter", "Ansoff", "Drucker"], c: "Kaplan and Norton" },
            { q: "The four perspectives of a Balanced Scorecard are:", o: ["Financial, Customer, Internal Process, Learning and Growth", "Sales, Production, HR, Finance", "Product, Price, Place, Promotion", "Strategy, Goals, Tasks, Results"], c: "Financial, Customer, Internal Process, Learning and Growth" },
            { q: "Inventory management involves:", o: ["Ordering, storing and using a company's inventory", "Selling products", "Hiring employees", "Calculating taxes"], c: "Ordering, storing and using a company's inventory" },
            { q: "ABC Analysis in inventory management classifies items based on:", o: ["Value and usage frequency", "Alphabetical order", "Weight", "Color"], c: "Value and usage frequency" },
            { q: "Economic Order Quantity (EOQ) is the order size that:", o: ["Minimises total inventory costs", "Maximises stock levels", "Is the smallest possible order", "None of the above"], c: "Minimises total inventory costs" },
            { q: "Plant layout refers to:", o: ["The physical arrangement of industrial facilities", "The design of a new product", "The marketing strategy", "The financial plan"], c: "The physical arrangement of industrial facilities" }
        ]
    },
    {
        setName: "Set 3",
        questions: [
            { q: "Process layout is best suited for:", o: ["Intermittent production", "Continuous production", "Mass production", "Standardised products"], c: "Intermittent production" },
            { q: "Product layout is suitable for:", o: ["Mass production of standardised items", "Custom orders", "Repair shops", "Job shops"], c: "Mass production of standardised items" },
            { q: "Capacity planning is -", o: ["Determining the production capacity needed by an organisation", "Designing a product", "Marketing products", "Managing employees"], c: "Determining the production capacity needed by an organisation" },
            { q: "Master Production Schedule (MPS) is:", o: ["A plan for individual commodities to be produced in each time period", "A list of employees", "A financial statement", "None of the above"], c: "A plan for individual commodities to be produced in each time period" },
            { q: "Material Requirements Planning (MRP) is used to:", o: ["Manage production processes and inventory", "Calculate payroll", "Design marketing campaigns", "None of the above"], c: "Manage production processes and inventory" },
            { q: "Project management involves:", o: ["Planning, executing, and closing projects", "Daily routine tasks", "Continuous manufacturing", "Selling products"], c: "Planning, executing, and closing projects" },
            { q: "The Critical Path Method (CPM) is used for:", o: ["Project scheduling", "Inventory control", "Accounting", "HR management"], c: "Project scheduling" },
            { q: "PERT stands for:", o: ["Program Evaluation and Review Technique", "Product Evaluation and Result Task", "Process Engineering and Routine Timing", "None of the above"], c: "Program Evaluation and Review Technique" },
            { q: "Maintenance management aims to:", o: ["Maintain production facilities and equipment in good working order", "Sell products", "Hire employees", "Increase prices"], c: "Maintain production facilities and equipment in good working order" },
            { q: "Preventive maintenance is:", o: ["Maintenance performed before a failure occurs", "Fixing machines after they break", "Replacing all machines every year", "None of the above"], c: "Maintenance performed before a failure occurs" },
            { q: "Breakdown maintenance is:", o: ["Maintenance performed after a failure occurs", "Regular check-ups", "Replacing machines periodically", "None of the above"], c: "Maintenance performed after a failure occurs" },
            { q: "Strategic control is concerned with:", o: ["Monitoring and evaluating the strategic management process", "Daily operations", "Short-term planning", "Employee attendance"], c: "Monitoring and evaluating the strategic management process" },
            { q: "Vertical integration occurs when a company:", o: ["Controls more than one stage of the supply chain", "Merges with a competitor", "Expands into a new industry", "None of the above"], c: "Controls more than one stage of the supply chain" },
            { q: "Horizontal integration occurs when a company:", o: ["Acquires or merges with a competitor", "Acquires a supplier", "Acquires a customer", "None of the above"], c: "Acquires or merges with a competitor" },
            { q: "Diversification involves:", o: ["Entering into new markets or product lines", "Focusing on a single product", "Reducing the number of products", "None of the above"], c: "Entering into new markets or product lines" },
            { q: "Market development is a strategy to:", o: ["Introduce existing products into new markets", "Develop new products for existing markets", "Sell more to existing customers", "None of the above"], c: "Introduce existing products into new markets" },
            { q: "Product development is a strategy to:", o: ["Introduce new products to existing markets", "Sell existing products to new markets", "Sell more to existing customers", "None of the above"], c: "Introduce new products to existing markets" },
            { q: "Market penetration is a strategy to:", o: ["Increase market share for existing products in existing markets", "Enter new markets", "Develop new products", "None of the above"], c: "Increase market share for existing products in existing markets" },
            { q: "Scenario planning is:", o: ["Analysing future possibilities to inform strategic decisions", "A daily checklist", "A past performance review", "None of the above"], c: "Analysing future possibilities to inform strategic decisions" },
            { q: "Strategic leadership involves:", o: ["Managing through others to influence the firm's future", "Supervising workers", "Accounting", "None of the above"], c: "Managing through others to influence the firm's future" },
            { q: "Organisational culture is:", o: ["The shared values and beliefs of an organisation", "The physical building", "The financial report", "The marketing plan"], c: "The shared values and beliefs of an organisation" },
            { q: "Globalisation is:", o: ["The process of interaction and integration among people and companies worldwide", "Selling in one city only", "Manufacturing in one factory", "None of the above"], c: "The process of interaction and integration among people and companies worldwide" },
            { q: "E-commerce refers to:", o: ["Buying and selling goods or services over the internet", "Trading at a local market", "Physical store sales", "None of the above"], c: "Buying and selling goods or services over the internet" },
            { q: "The Ansoff Matrix is used for:", o: ["Identifying growth opportunities", "Calculating debt", "Managing employees", "Designing products"], c: "Identifying growth opportunities" },
            { q: "Resource allocation is:", o: ["Distributing resources to various projects or business units", "Buying new machines", "Hiring staff", "None of the above"], c: "Distributing resources to various projects or business units" }
        ]
    },
    {
        setName: "Set 4",
        questions: [
            { q: "Strategic change management is:", o: ["Managing the process of implementing new strategies", "Making small daily adjustments", "Avoiding change", "None of the above"], c: "Managing the process of implementing new strategies" },
            { q: "Gap analysis in strategic management is:", o: ["Comparing actual performance with potential or desired performance", "Measuring the distance between factories", "Identifying employee skills", "None of the above"], c: "Comparing actual performance with potential or desired performance" },
            { q: "Productivity is defined as:", o: ["The ratio of output to input", "The total amount of output", "The total cost of production", "The number of employees"], c: "The ratio of output to input" },
            { q: "Labour productivity is -", o: ["Total output / Total labour hours", "Total output / Total material cost", "Total output / Total capital", "None of the above"], c: "Total output / Total labour hours" },
            { q: "Capital productivity is -", o: ["Total output / Total capital invested", "Total output / Total labour hours", "Total output / Total energy", "None of the above"], c: "Total output / Total capital invested" },
            { q: "Material productivity is -", o: ["Total output / Total material quantity", "Total output / Total cost", "Total output / Total time", "None of the above"], c: "Total output / Total material quantity" },
            { q: "Total Factor Productivity (TFP) measures:", o: ["Efficiency of all inputs used in production", "Only labour efficiency", "Only capital efficiency", "Only energy efficiency"], c: "Efficiency of all inputs used in production" },
            { q: "Work study consists of:", o: ["Method study and Work measurement", "Hiring and training", "Selling and distribution", "Accounting and finance"], c: "Method study and Work measurement" },
            { q: "Method study aims to:", o: ["Find a better and more efficient way of doing work", "Measure how long it takes to do work", "Calculate wages", "Reduce staff"], c: "Find a better and more efficient way of doing work" },
            { q: "Work measurement aims to:", o: ["Determine the time required for a task", "Redesign the work area", "Improve employee morale", "None of the above"], c: "Determine the time required for a task" },
            { q: "Standard time is -", o: ["Normal time plus allowances", "The time it takes an average worker", "The total time of a shift", "None of the above"], c: "Normal time plus allowances" },
            { q: "Production planning and control (PPC) involves:", o: ["Routing, Scheduling, Dispatching, Follow-up", "Marketing, Sales, Promotion", "Accounting, Finance, Audit", "HR, Training, Recruitment"], c: "Routing, Scheduling, Dispatching, Follow-up" },
            { q: "Routing determines:", o: ["The path or sequence of operations", "The time of each operation", "The cost of each operation", "None of the above"], c: "The path or sequence of operations" },
            { q: "Scheduling determines:", o: ["When each task should start and finish", "Where each task is performed", "Who performs each task", "None of the above"], c: "When each task should start and finish" },
            { q: "Dispatching involves:", o: ["The actual starting of production", "Monitoring progress", "Planning for the future", "None of the above"], c: "The actual starting of production" },
            { q: "Gantt charts are used for:", o: ["Project scheduling and tracking", "Inventory control", "Accounting", "HR management"], c: "Project scheduling and tracking" },
            { q: "Value engineering (VE) is used to:", o: ["Maximise value by reducing costs without reducing quality", "Increase prices", "Reduce quality to save cost", "None of the above"], c: "Maximise value by reducing costs without reducing quality" },
            { q: "Reliability of a product is:", o: ["The probability that it will perform its intended function over a period", "The price of the product", "The color of the product", "The size of the product"], c: "The probability that it will perform its intended function over a period" },
            { q: "Maintainability is:", o: ["The ease with which a product can be repaired or maintained", "The total life of a product", "The cost of production", "None of the above"], c: "The ease with which a product can be repaired or maintained" },
            { q: "Aggregate planning involves:", o: ["Planning for production over a medium-term period", "Daily scheduling", "Long-term vision planning", "None of the above"], c: "Planning for production over a medium-term period" },
            { q: "Quality circles are:", o: ["Small groups of employees who meet to solve quality-related problems", "Department managers", "External auditors", "None of the above"], c: "Small groups of employees who meet to solve quality-related problems" },
            { q: "ISO 9000 is a set of standards for:", o: ["Quality management systems", "Environmental management", "Health and safety", "None of the above"], c: "Quality management systems" },
            { q: "ISO 14000 is a set of standards for:", o: ["Environmental management systems", "Quality management", "Health and safety", "None of the above"], c: "Environmental management systems" },
            { q: "Kaizen is a Japanese term meaning:", o: ["Continuous improvement", "Big change", "Total quality", "None of the above"], c: "Continuous improvement" },
            { q: "Kanban is a system used in JIT for:", o: ["Visual signal to trigger production or movement of items", "Hiring employees", "Calculating profits", "None of the above"], c: "Visual signal to trigger production or movement of items" }
        ]
    },
    {
        setName: "Set 5",
        questions: [
            { q: "FMS stands for:", o: ["Flexible Manufacturing System", "Fixed Maintenance System", "Fast Material Supply", "None of the above"], c: "Flexible Manufacturing System" },
            { q: "CIM stands for:", o: ["Computer Integrated Manufacturing", "Continuous Improvement Management", "Corporate Investment Management", "None of the above"], c: "Computer Integrated Manufacturing" },
            { q: "CAD stands for:", o: ["Computer-Aided Design", "Continuous Auto Design", "Corporate Allied Development", "None of the above"], c: "Computer-Aided Design" },
            { q: "CAM stands for:", o: ["Computer-Aided Manufacturing", "Continuous Allied Management", "Corporate Asset Maintenance", "None of the above"], c: "Computer-Aided Manufacturing" },
            { q: "Supply chain management (SCM) involves:", o: ["Flow of goods and services from raw materials to final products", "Only transportation", "Only storage", "Only selling"], c: "Flow of goods and services from raw materials to final products" },
            { q: "Third-party logistics (3PL) involves:", o: ["Outsourcing logistics functions to a third party", "Internal logistics management", "Buying a new truck", "None of the above"], c: "Outsourcing logistics functions to a third party" },
            { q: "Reverse logistics involves:", o: ["Managing the return of goods from customers", "Sending goods to customers", "Ordering raw materials", "None of the above"], c: "Managing the return of goods from customers" },
            { q: "RFID stands for:", o: ["Radio Frequency Identification", "Real-time Field Identification", "Rapid Frequency ID", "None of the above"], c: "Radio Frequency Identification" },
            { q: "ERP stands for:", o: ["Enterprise Resource Planning", "Employee Relations Planning", "Extended Resource Process", "None of the above"], c: "Enterprise Resource Planning" },
            { q: "Forecasting methods can be:", o: ["Qualitative and Quantitative", "Only numerical", "Only based on opinion", "None of the above"], c: "Qualitative and Quantitative" },
            { q: "Delphi method is a:", o: ["Qualitative forecasting technique using a panel of experts", "Quantitative forecasting technique", "Method of production", "None of the above"], c: "Qualitative forecasting technique using a panel of experts" },
            { q: "Time series analysis is a:", o: ["Quantitative forecasting technique based on historical data", "Qualitative forecasting technique", "Method of accounting", "None of the above"], c: "Quantitative forecasting technique based on historical data" },
            { q: "Moving average is a technique used in:", o: ["Time series forecasting", "Project management", "HR management", "None of the above"], c: "Time series forecasting" },
            { q: "Exponential smoothing is a technique used in:", o: ["Time series forecasting", "Product design", "PESTEL analysis", "None of the above"], c: "Time series forecasting" },
            { q: "Correlation and regression are used in:", o: ["Causal forecasting", "JIT", "Lean manufacturing", "None of the above"], c: "Causal forecasting" },
            { q: "Safety stock is maintained to:", o: ["Guard against uncertainty in supply or demand", "Maximise storage cost", "Stop production", "None of the above"], c: "Guard against uncertainty in supply or demand" },
            { q: "Lead time is:", o: ["The time between placing an order and receiving it", "The time to sell a product", "The time to design a product", "None of the above"], c: "The time between placing an order and receiving it" },
            { q: "Reorder point is the level of inventory at which:", o: ["An order must be placed", "The inventory is zero", "The inventory is at its maximum", "None of the above"], c: "An order must be placed" },
            { q: "Material handling is the movement of materials:", o: ["Within a facility", "Between cities", "Globally", "None of the above"], c: "Within a facility" },
            { q: "Standardisation means:", o: ["Reducing diversity in products and processes", "Increasing diversity", "Keeping everything unique", "None of the above"], c: "Reducing diversity in products and processes" },
            { q: "Simplification means:", o: ["Reducing complexity in products and processes", "Making things more complex", "Adding more features", "None of the above"], c: "Reducing complexity in products and processes" },
            { q: "Automation involves:", o: ["Using technology to perform tasks with minimal human intervention", "Hiring more workers", "Manual production", "None of the above"], c: "Using technology to perform tasks with minimal human intervention" },
            { q: "Strategic thinking involves:", o: ["A cognitive process to create sustainable competitive advantage", "Following a manual", "Routine thinking", "None of the above"], c: "A cognitive process to create sustainable competitive advantage" },
            { q: "The 'Five Forces' model was developed by:", o: ["Michael Porter", "Igor Ansoff", "Philip Kotler", "None of the above"], c: "Michael Porter" },
            { q: "Porter's Five Forces are:", o: ["Threat of new entrants, Bargaining power of suppliers, Bargaining power of buyers, Threat of substitutes, Industry rivalry", "Strengths, Weaknesses, Opportunities, Threats, Success", "Product, Price, Place, Promotion, Process", "None of the above"], c: "Threat of new entrants, Bargaining power of suppliers, Bargaining power of buyers, Threat of substitutes, Industry rivalry" }
        ]
    },
    {
        setName: "Set 6",
        questions: [
            { q: "Corporate governance is:", o: ["The system by which companies are directed and controlled", "The marketing plan", "The production schedule", "None of the above"], c: "The system by which companies are directed and controlled" },
            { q: "Ethics in business refers to:", o: ["Applied ethics that examines ethical principles and moral or ethical problems in business", "Increasing profits at any cost", "Avoiding all taxes", "None of the above"], c: "Applied ethics that examines ethical principles and moral or ethical problems in business" },
            { q: "Sustainability in business refers to:", o: ["Managing the triple bottom line (social, environmental, financial)", "Maintaining current production only", "Increasing debts", "None of the above"], c: "Managing the triple bottom line (social, environmental, financial)" },
            { q: "Strategic Management process includes:", o: ["Formulation, Implementation, Evaluation", "Planning, Doing, Checking", "Idea, Launch, Peak", "None of the above"], c: "Formulation, Implementation, Evaluation" },
            { q: "Environmental scanning is:", o: ["Monitoring, evaluating, and disseminating information from the external and internal environments", "Cleaning the factory", "Reducing waste", "None of the above"], c: "Monitoring, evaluating, and disseminating information from the external and internal environments" },
            { q: "A 'Question Mark' in the BCG matrix represents:", o: ["Low market share, high market growth", "High market share, low market growth", "Low market share, low market growth", "High market share, high market growth"], c: "Low market share, high market growth" },
            { q: "Vertical integration is a type of:", o: ["Corporate level strategy", "Business level strategy", "Functional level strategy", "None of the above"], c: "Corporate level strategy" },
            { q: "Horizontal integration is a type of:", o: ["Corporate level strategy", "Business level strategy", "Functional level strategy", "None of the above"], c: "Corporate level strategy" },
            { q: "Concentric diversification is:", o: ["Entering a new business related to current business", "Entering a completely unrelated business", "Reducing products", "None of the above"], c: "Entering a new business related to current business" },
            { q: "Conglomerate diversification is:", o: ["Entering a completely unrelated business", "Entering a related business", "Merging with a competitor", "None of the above"], c: "Entering a completely unrelated business" },
            { q: "Retrenchment strategy involves:", o: ["Reducing the scope of activities", "Expanding activities", "Launching new products", "None of the above"], c: "Reducing the scope of activities" },
            { q: "Divestment strategy involves:", o: ["Selling a business unit or product line", "Buying a new company", "Increasing investment", "None of the above"], c: "Selling a business unit or product line" },
            { q: "Liquidation strategy involves:", o: ["Closing down the business and selling its assets", "Expanding globally", "Acquiring a competitor", "None of the above"], c: "Closing down the business and selling its assets" },
            { q: "Turnaround strategy is used to:", o: ["Recover from poor performance", "Close the business", "Merge with another firm", "None of the above"], c: "Recover from poor performance" },
            { q: "Blue Ocean strategy focuses on:", o: ["Creating uncontested market space", "Competing in existing markets", "Price wars", "None of the above"], c: "Creating uncontested market space" },
            { q: "Red Ocean strategy focuses on:", o: ["Competing in existing markets", "Creating new markets", "Innovation", "None of the above"], c: "Competing in existing markets" },
            { q: "The 'Extended Enterprise' concept refers to:", o: ["A network of organisations involved in the entire product cycle", "A large company building", "A multinational corporation only", "None of the above"], c: "A network of organisations involved in the entire product cycle" },
            { q: "Mass customisation is:", o: ["Providing large quantities of customised products", "Producing standardised items in large quantities", "Handcrafting products", "None of the above"], c: "Providing large quantities of customised products" },
            { q: "Business model is:", o: ["The plan for how a company generates revenue and profit", "The design of the product", "The marketing logo", "None of the above"], c: "The plan for how a company generates revenue and profit" },
            { q: "Strategic risk is:", o: ["The risk that a company's strategy will become ineffective", "Operational failure", "Financial theft", "None of the above"], c: "The risk that a company's strategy will become ineffective" },
            { q: "Innovation management is:", o: ["The process of managing an organisation's innovation procedure", "Buying new machines only", "Increasing prices", "None of the above"], c: "The process of managing an organisation's innovation procedure" },
            { q: "Knowledge management is:", o: ["Creating, sharing, using and managing the knowledge of an organisation", "Filing papers", "Hiring experts only", "None of the above"], c: "Creating, sharing, using and managing the knowledge of an organisation" },
            { q: "Outsourcing is:", o: ["Obtaining goods or services from an outside supplier", "Manufacturing everything internally", "Exporting goods", "None of the above"], c: "Obtaining goods or services from an outside supplier" },
            { q: "Offshoring is:", o: ["Relocating business processes to another country", "Selling goods abroad", "Importing raw materials", "None of the above"], c: "Relocating business processes to another country" },
            { q: "Mergers and acquisitions (M&A) are:", o: ["Corporate strategies to grow and consolidate", "Short-term projects", "Small changes", "None of the above"], c: "Corporate strategies to grow and consolidate" }
        ]
    },
    {
        setName: "Set 7",
        questions: [
            { q: "Strategic fit refers to:", o: ["The degree to which an organisation matches its resources and capabilities with the external environment", "The size of the office", "The number of employees", "None of the above"], c: "The degree to which an organisation matches its resources and capabilities with the external environment" },
            { q: "Capabilities are:", o: ["The ability of an organisation to exploit its resources", "Only physical assets", "Only financial assets", "None of the above"], c: "The ability of an organisation to exploit its resources" },
            { q: "Core competencies are:", o: ["Unique strengths that give an organisation a competitive advantage", "Basic tasks everyone can do", "Daily routine work", "None of the above"], c: "Unique strengths that give an organisation a competitive advantage" },
            { q: "Dynamic capabilities are:", o: ["An organisation's ability to renew and change its competencies to suit the environment", "Fixed skills", "Old methods", "None of the above"], c: "An organisation's ability to renew and change its competencies to suit the environment" },
            { q: "Resource-Based View (RBV) is a framework to:", o: ["Determine the strategic resources a firm can exploit to achieve sustainable competitive advantage", "Calculate total assets", "Manage payroll", "None of the above"], c: "Determine the strategic resources a firm can exploit to achieve sustainable competitive advantage" },
            { q: "VRIO framework stands for:", o: ["Value, Rarity, Imitability, Organisation", "Volume, Rate, Intent, Operations", "Vision, Result, Impact, Outcome", "None of the above"], c: "Value, Rarity, Imitability, Organisation" },
            { q: "Game theory is used in strategic management to:", o: ["Analyse competitive situations and decision-making", "Play video games", "Manage sports teams", "None of the above"], c: "Analyse competitive situations and decision-making" },
            { q: "Mintzberg's 5Ps of Strategy are:", o: ["Plan, Ploy, Pattern, Position, Perspective", "Product, Price, Place, Promotion, Process", "People, Profit, Planet, Power, Passion", "None of the above"], c: "Plan, Ploy, Pattern, Position, Perspective" },
            { q: "Emergent strategy is:", o: ["Strategy that develops over time in response to unforeseen circumstances", "Strategy that is planned from the start", "Strategy that fails", "None of the above"], c: "Strategy that develops over time in response to unforeseen circumstances" },
            { q: "Intended strategy is:", o: ["Strategy that an organisation plans to follow", "Strategy that happens by accident", "Strategy that is forced by government", "None of the above"], c: "Strategy that an organisation plans to follow" },
            { q: "Deliberate strategy is:", o: ["Strategy that is successfully implemented as intended", "Strategy that is changed midway", "Strategy that fails", "None of the above"], c: "Strategy that is successfully implemented as intended" },
            { q: "Unrealised strategy is:", o: ["Strategy that is intended but not implemented", "Strategy that works perfectly", "Strategy that is emergent", "None of the above"], c: "Strategy that is intended but not implemented" },
            { q: "Realised strategy is:", o: ["The strategy that actually takes place", "The strategy that was only planned", "The strategy that failed", "None of the above"], c: "The strategy that actually takes place" },
            { q: "Strategic drift occurs when:", o: ["Strategy fails to keep pace with changing environment", "Strategy changes too quickly", "The company moves to a new city", "None of the above"], c: "Strategy fails to keep pace with changing environment" },
            { q: "PESTEL analysis factors are:", o: ["Political, Economic, Social, Technological, Environmental, Legal", "Production, Employee, Sales, Task, Equipment, Labour", "Plan, Evaluate, Study, Track, Execute, Learn", "None of the above"], c: "Political, Economic, Social, Technological, Environmental, Legal" },
            { q: "Scenario planning helps to:", o: ["Reduce uncertainty by preparing for multiple futures", "Predict the exact future", "Ignore future trends", "None of the above"], c: "Reduce uncertainty by preparing for multiple futures" },
            { q: "Competitive intelligence is:", o: ["Gathering and analysing information about competitors", "Spying on employees", "Selling secrets", "None of the above"], c: "Gathering and analysing information about competitors" },
            { q: "Market fragmentation occurs when:", o: ["A market is divided into many small segments with no clear leader", "A single firm dominates the market", "The market is growing rapidly", "None of the above"], c: "A market is divided into many small segments with no clear leader" },
            { q: "Product differentiation is:", o: ["Making a product unique to appeal to a specific target market", "Making all products identical", "Reducing product features", "None of the above"], c: "Making a product unique to appeal to a specific target market" },
            { q: "Price leadership occurs when:", o: ["One firm sets the price for the entire industry", "All firms have different prices", "Customers set the prices", "None of the above"], c: "One firm sets the price for the entire industry" },
            { q: "First-mover advantage is:", o: ["The competitive advantage gained by being the first to enter a market", "Being the last to enter a market", "Following a competitor", "None of the above"], c: "The competitive advantage gained by being the first to enter a market" },
            { q: "Second-mover advantage is:", o: ["Gaining advantage by following the first mover and learning from their mistakes", "Being the leader", "Failing after the first mover", "None of the above"], c: "Gaining advantage by following the first mover and learning from their mistakes" },
            { q: "Niche market is:", o: ["A small, specialised segment of a larger market", "The entire global market", "A mass market", "None of the above"], c: "A small, specialised segment of a larger market" },
            { q: "Economies of scale are:", o: ["Cost advantages gained by an increased level of production", "Higher costs for more production", "Small production levels only", "None of the above"], c: "Cost advantages gained by an increased level of production" },
            { q: "Economies of scope are:", o: ["Cost advantages gained by producing a variety of products", "Cost advantages of high volume only", "Reducing the number of products", "None of the above"], c: "Cost advantages gained by producing a variety of products" }
        ]
    },
    {
        setName: "Set 8",
        questions: [
            { q: "Strategic group analysis is:", o: ["Analysing firms within an industry that follow similar strategies", "Analysing all employees", "Analysing government policies", "None of the above"], c: "Analysing firms within an industry that follow similar strategies" },
            { q: "Core rigidities are:", o: ["Core competencies that have become obsolete or harmful", "Strong new skills", "Flexible capabilities", "None of the above"], c: "Core competencies that have become obsolete or harmful" },
            { q: "Value chain linkages are:", o: ["Connections between different activities in the value chain", "Physical chains in the factory", "Links to external websites", "None of the above"], c: "Connections between different activities in the value chain" },
            { q: "Strategic outsourcing is:", o: ["Outsourcing non-core activities to focus on core competencies", "Outsourcing everything", "Doing everything internally", "None of the above"], c: "Outsourcing non-core activities to focus on core competencies" },
            { q: "Offshoring is motivated by:", o: ["Cost reduction and access to global talent", "Increasing domestic taxes", "Reducing global sales", "None of the above"], c: "Cost reduction and access to global talent" },
            { q: "Global strategy involves:", o: ["Standardised products and global integration", "Local products for local markets only", "Small city sales", "None of the above"], c: "Standardised products and global integration" },
            { q: "Multi-domestic strategy involves:", o: ["Customising products to local market needs", "Standardising everything globally", "No international sales", "None of the above"], c: "Customising products to local market needs" },
            { q: "Transnational strategy involves:", o: ["Balancing global integration with local responsiveness", "Only global integration", "Only local responsiveness", "None of the above"], c: "Balancing global integration with local responsiveness" },
            { q: "Licensing is:", o: ["Allowing another firm to use your intellectual property for a fee", "Selling your company", "Merging with a firm", "None of the above"], c: "Allowing another firm to use your intellectual property for a fee" },
            { q: "Franchising is:", o: ["A type of licensing where a firm provides a complete business model", "Buying a new factory", "Hiring new staff", "None of the above"], c: "A type of licensing where a firm provides a complete business model" },
            { q: "Joint venture is:", o: ["A new entity created by two or more parent firms", "A merger", "An acquisition", "None of the above"], c: "A new entity created by two or more parent firms" },
            { q: "Wholly owned subsidiary is:", o: ["A business unit owned 100% by the parent company", "A joint venture", "A licensed partner", "None of the above"], c: "A business unit owned 100% by the parent company" },
            { q: "Strategic implementation is:", o: ["The process of putting strategy into action", "Thinking about strategy", "Planning for the future", "None of the above"], c: "The process of putting strategy into action" },
            { q: "Organisational structure is:", o: ["The formal system of task and reporting relationships", "The physical building", "The financial plan", "None of the above"], c: "The formal system of task and reporting relationships" },
            { q: "Functional structure is:", o: ["Organising by departments (marketing, finance, etc.)", "Organising by products", "Organising by geography", "None of the above"], c: "Organising by departments (marketing, finance, etc.)" },
            { q: "Divisional structure is:", o: ["Organising by business units or product lines", "Organising by functions", "A flat structure", "None of the above"], c: "Organising by business units or product lines" },
            { q: "Matrix structure is:", o: ["Dual reporting relationships (functional and project/product)", "Single reporting line", "No reporting lines", "None of the above"], c: "Dual reporting relationships (functional and project/product)" },
            { q: "Strategic control systems are:", o: ["Formal target-setting, measurement, and feedback systems", "Daily checklists", "Unstructured feedback", "None of the above"], c: "Formal target-setting, measurement, and feedback systems" },
            { q: "KPI stands for:", o: ["Key Performance Indicator", "Knowledge Process Index", "Key Productivity Item", "None of the above"], c: "Key Performance Indicator" },
            { q: "Strategic leadership is critical for:", o: ["Communicating vision and inspiring change", "Routine task management only", "Accounting only", "None of the above"], c: "Communicating vision and inspiring change" },
            { q: "Resistance to change is:", o: ["The tendency to maintain the status quo", "The desire for change", "Implementing new technology", "None of the above"], c: "The tendency to maintain the status quo" },
            { q: "Change agents are:", o: ["Individuals who lead or facilitate change", "People who resist change", "External competitors", "None of the above"], c: "Individuals who lead or facilitate change" },
            { q: "Lewin's change model consists of:", o: ["Unfreeze, Change, Refreeze", "Plan, Do, Check", "Start, Middle, End", "None of the above"], c: "Unfreeze, Change, Refreeze" },
            { q: "Corporate entrepreneurship is:", o: ["Entrepreneurial activities within an existing organisation", "Starting a new small business only", "Buying stocks", "None of the above"], c: "Entrepreneurial activities within an existing organisation" },
            { q: "Strategic renewal is:", o: ["The process of refreshing or replacing core competencies", "Buying new office furniture", "Changing the company name only", "None of the above"], c: "The process of refreshing or replacing core competencies" }
        ]
    },
    {
        setName: "Set 9",
        questions: [
            { q: "Disruptive innovation is:", o: ["Innovation that creates a new market and value network", "Small improvements", "Maintaining existing markets", "None of the above"], c: "Innovation that creates a new market and value network" },
            { q: "Incremental innovation is:", o: ["Small, continuous improvements to existing products/processes", "Radical change", "New markets", "None of the above"], c: "Small, continuous improvements to existing products/processes" },
            { q: "Radical innovation is:", o: ["Fundamental change that transforms an industry", "Small changes", "Daily updates", "None of the above"], c: "Fundamental change that transforms an industry" },
            { q: "Open innovation is:", o: ["Using external and internal ideas to advance technology", "Keeping all ideas secret", "Only using internal R&D", "None of the above"], c: "Using external and internal ideas to advance technology" },
            { q: "Digital transformation is:", o: ["The integration of digital technology into all areas of a business", "Buying a new computer", "Using email only", "None of the above"], c: "The integration of digital technology into all areas of a business" },
            { q: "Big data analytics is:", o: ["Analysing large data sets to uncover patterns and trends", "Counting inventory manually", "A small spreadsheet", "None of the above"], c: "Analysing large data sets to uncover patterns and trends" },
            { q: "Artificial intelligence (AI) in strategy is:", o: ["Using machines to simulate human intelligence for decision-making", "Manual data entry", "Basic calculators", "None of the above"], c: "Using machines to simulate human intelligence for decision-making" },
            { q: "Blockchain technology provides:", o: ["A decentralised and transparent record of transactions", "A central database", "A physical chain", "None of the above"], c: "A decentralised and transparent record of transactions" },
            { q: "Strategic agility is:", o: ["The ability of an organisation to move quickly and easily in response to change", "Being rigid and slow", "Following old plans strictly", "None of the above"], c: "The ability of an organisation to move quickly and easily in response to change" },
            { q: "Strategic resilience is:", o: ["The ability to recover quickly from difficulties", "Failing easily", "Never facing challenges", "None of the above"], c: "The ability to recover quickly from difficulties" },
            { q: "Shared value is:", o: ["Creating economic value in a way that also creates value for society", "Only increasing shareholder wealth", "Reducing all value", "None of the above"], c: "Creating economic value in a way that also creates value for society" },
            { q: "Stakeholder theory suggests that:", o: ["Managers should balance the interests of all stakeholders", "Only shareholders matter", "Only employees matter", "None of the above"], c: "Managers should balance the interests of all stakeholders" },
            { q: "ESG criteria in strategy refers to:", o: ["Environmental, Social, and Governance factors", "Employee, Sales, and Growth", "Equipment, Storage, and Goods", "None of the above"], c: "Environmental, Social, and Governance factors" },
            { q: "Circular economy aims to:", o: ["Minimise waste and make the most of resources", "Increase waste", "Linear production (take-make-waste)", "None of the above"], c: "Minimise waste and make the most of resources" },
            { q: "Supply chain resilience is:", o: ["The ability of a supply chain to recover from disruptions", "A fragile supply chain", "A very slow supply chain", "None of the above"], c: "The ability of a supply chain to recover from disruptions" },
            { q: "Dynamic pricing is:", o: ["Adjusting prices in real-time based on demand and supply", "Fixed prices for all time", "Prices set by government only", "None of the above"], c: "Adjusting prices in real-time based on demand and supply" },
            { q: "Platform business models:", o: ["Facilitate value creation by connecting different groups", "Only sell one product", "Are physical stores only", "None of the above"], c: "Facilitate value creation by connecting different groups" },
            { q: "Strategic foresight is:", o: ["Anticipating future developments to inform strategy", "Reviewing past failures only", "Daily routine tasks", "None of the above"], c: "Anticipating future developments to inform strategy" },
            { q: "Lean startup methodology involves:", o: ["Build-Measure-Learn feedback loop", "Long-term detailed planning before launch", "Large initial investment", "None of the above"], c: "Build-Measure-Learn feedback loop" },
            { q: "Agile management is:", o: ["An iterative approach to managing projects and teams", "Waterfall methodology strictly", "Bureaucratic management", "None of the above"], c: "An iterative approach to managing projects and teams" },
            { q: "Design thinking is:", o: ["A human-centred approach to innovation and problem-solving", "Only about product aesthetics", "A technical engineering manual", "None of the above"], c: "A human-centred approach to innovation and problem-solving" },
            { q: "Growth hacking is:", o: ["Rapid experimentation across marketing and product development for growth", "Slow traditional marketing only", "Reducing growth", "None of the above"], c: "Rapid experimentation across marketing and product development for growth" },
            { q: "Strategic alignment is:", o: ["Ensuring all parts of an organisation work towards the same goals", "Different departments having different goals", "Ignoring strategy", "None of the above"], c: "Ensuring all parts of an organisation work towards the same goals" },
            { q: "Performance management is:", o: ["Ensuring that organisational goals are consistently met in an efficient manner", "Only reviewing end-of-year results", "Ignoring employee performance", "None of the above"], c: "Ensuring that organisational goals are consistently met in an efficient manner" },
            { q: "Change management tools include:", o: ["Communication plans, training, coaching, resistance management", "Only firing employees", "Ignoring employee concerns", "None of the above"], c: "Communication plans, training, coaching, resistance management" }
        ]
    },
    {
        setName: "Set 10",
        questions: [
            { q: "Strategic evaluation involves:", o: ["Measuring performance against goals and taking corrective action", "Doing nothing", "Starting a new business", "None of the above"], c: "Measuring performance against goals and taking corrective action" },
            { q: "Strategic gap is:", o: ["The difference between desired performance and actual performance", "The distance between two factories", "A hole in the wall", "None of the above"], c: "The difference between desired performance and actual performance" },
            { q: "Resource auditing is:", o: ["Evaluating the quantity and quality of an organisation's resources", "Checking the cash register only", "Ignoring assets", "None of the above"], c: "Evaluating the quantity and quality of an organisation's resources" },
            { q: "Benchmarking types are:", o: ["Internal, Competitive, Functional, Generic", "Only internal", "Only external", "None of the above"], c: "Internal, Competitive, Functional, Generic" },
            { q: "Strategic choice involves:", o: ["Selecting the most appropriate strategy from alternatives", "Doing what everyone else does", "Flipping a coin", "None of the above"], c: "Selecting the most appropriate strategy from alternatives" },
            { q: "Strategy evaluation criteria are:", o: ["Suitability, Feasibility, Acceptability", "Product, Price, Place", "Strength, Weakness, Task", "None of the above"], c: "Suitability, Feasibility, Acceptability" },
            { q: "Suitability refers to:", o: ["Whether the strategy addresses the key strategic issues", "Whether the strategy is cheap", "Whether employees like it", "None of the above"], c: "Whether the strategy addresses the key strategic issues" },
            { q: "Feasibility refers to:", o: ["Whether the organisation has the resources to implement the strategy", "Whether the strategy is exciting", "Whether it's legal", "None of the above"], c: "Whether the organisation has the resources to implement the strategy" },
            { q: "Acceptability refers to:", o: ["Whether the expected performance outcomes meet the expectations of stakeholders", "Whether the manager likes it", "Whether it's a new idea", "None of the above"], c: "Whether the expected performance outcomes meet the expectations of stakeholders" },
            { q: "Implementation plan is:", o: ["A detailed plan outlining the steps, timeline, and responsibilities for execution", "A vague idea", "A past report", "None of the above"], c: "A detailed plan outlining the steps, timeline, and responsibilities for execution" },
            { q: "Strategic communication is:", o: ["Communicating the strategy to all stakeholders", "Keeping strategy secret", "Only telling the CEO", "None of the above"], c: "Communicating the strategy to all stakeholders" },
            { q: "Strategic review is:", o: ["Regularly reviewing the strategy's performance and environment", "Reviewing once every 10 years", "Never reviewing", "None of the above"], c: "Regularly reviewing the strategy's performance and environment" },
            { q: "Change management strategies include:", o: ["Education, participation, facilitation, negotiation, manipulation, coercion", "Only coercion", "Only education", "None of the above"], c: "Education, participation, facilitation, negotiation, manipulation, coercion" },
            { q: "Organisational learning is:", o: ["The process of creating, retaining, and transferring knowledge within an organisation", "Employees going to school", "Reading a book", "None of the above"], c: "The process of creating, retaining, and transferring knowledge within an organisation" },
            { q: "Continuous improvement involves:", o: ["Ongoing efforts to improve products, services, or processes", "Improving once and stopping", "Avoiding all improvements", "None of the above"], c: "Ongoing efforts to improve products, services, or processes" },
            { q: "Corporate parenting is:", o: ["The role of a corporate headquarters in managing its business units", "Managing employees' families", "Hiring parents only", "None of the above"], c: "The role of a corporate headquarters in managing its business units" },
            { q: "Synergy occurs when:", o: ["The whole is greater than the sum of its parts", "The parts are separate", "The whole is less than its parts", "None of the above"], c: "The whole is greater than the sum of its parts" },
            { q: "Portfolio management involves:", o: ["Managing a collection of business units or products", "Managing one product only", "Buying one stock", "None of the above"], c: "Managing a collection of business units or products" },
            { q: "Strategic focus is:", o: ["Concentrating on specific goals and activities", "Doing everything at once", "Having no clear goals", "None of the above"], c: "Concentrating on specific goals and activities" },
            { q: "Execution excellence is:", o: ["Consistently and effectively implementing strategies", "Having a good idea but no action", "Failing in implementation", "None of the above"], c: "Consistently and effectively implementing strategies" },
            { q: "Leadership styles in strategy can be:", o: ["Transformational, Transactional, Autocratic, Democratic", "Only transformational", "Only autocratic", "None of the above"], c: "Transformational, Transactional, Autocratic, Democratic" },
            { q: "Team building is:", o: ["Improving interpersonal relations and social interactions within teams", "Building a physical wall", "Hiring individual contractors only", "None of the above"], c: "Improving interpersonal relations and social interactions within teams" },
            { q: "Conflict management involves:", o: ["Identifying and handling conflicts sensibly and efficiently", "Ignoring all conflicts", "Starting more conflicts", "None of the above"], c: "Identifying and handling conflicts sensibly and efficiently" },
            { q: "Motivation theories in strategy help to:", o: ["Understand what drives employee performance", "Calculate debt", "Design products", "None of the above"], c: "Understand what drives employee performance" },
            { q: "Strategic milestones are:", o: ["Key progress points in a strategic implementation", "Physical stones", "End of the company", "None of the above"], c: "Key progress points in a strategic implementation" }
        ]
    },
    {
        setName: "Set 11",
        questions: [
            { q: "Monitoring and evaluation (M&E) is:", o: ["The process of tracking and assessing progress and impact", "Reviewing past only", "Planning future only", "None of the above"], c: "The process of tracking and assessing progress and impact" },
            { q: "Feedback loops are:", o: ["Systems where outputs are used as inputs for future actions", "Circular paths in a factory", "Endless emails", "None of the above"], c: "Systems where outputs are used as inputs for future actions" },
            { q: "Corrective action is:", o: ["Action taken to fix a deviation from a plan", "Doing nothing", "Starting over completely", "None of the above"], c: "Action taken to fix a deviation from a plan" },
            { q: "Strategic adaptation is:", o: ["Modifying the strategy in response to environmental changes", "Staying with the same strategy forever", "Avoiding change", "None of the above"], c: "Modifying the strategy in response to environmental changes" },
            { q: "Business ethics values include:", o: ["Integrity, honesty, fairness, responsibility", "Greed and deception", "Selfishness", "None of the above"], c: "Integrity, honesty, fairness, responsibility" },
            { q: "Corporate social responsibility (CSR) dimensions are:", o: ["Economic, Legal, Ethical, Philanthropic", "Sales, Marketing, HR, Finance", "Product, Price, Place, Promotion", "None of the above"], c: "Economic, Legal, Ethical, Philanthropic" },
            { q: "Environmental sustainability involves:", o: ["Protecting and managing natural resources", "Using all resources up", "Increasing pollution", "None of the above"], c: "Protecting and managing natural resources" },
            { q: "Social responsibility involves:", o: ["Considering the impact of business decisions on society", "Ignoring community needs", "Only increasing profit", "None of the above"], c: "Considering the impact of business decisions on society" },
            { q: "Ethical decision-making is:", o: ["Making choices that are consistent with ethical principles", "Making choices based on profit only", "Making random choices", "None of the above"], c: "Making choices that are consistent with ethical principles" },
            { q: "Corporate culture can be a:", o: ["Source of competitive advantage", "Physical asset", "Financial report", "None of the above"], c: "Source of competitive advantage" },
            { q: "Leadership and culture are:", o: ["Closely linked in shaping an organisation", "Completely separate", "Only for big companies", "None of the above"], c: "Closely linked in shaping an organisation" },
            { q: "Strategic change can be:", o: ["Incremental or radical", "Only radical", "Only incremental", "None of the above"], c: "Incremental or radical" },
            { q: "Change management process involves:", o: ["Planning, implementing, and sustaining change", "Thinking about change only", "Ignoring resistance", "None of the above"], c: "Planning, implementing, and sustaining change" },
            { q: "Communicating change is critical to:", o: ["Reduce uncertainty and resistance", "Increase confusion", "Hide information", "None of the above"], c: "Reduce uncertainty and resistance" },
            { q: "Employee engagement in change leads to:", o: ["Better implementation outcomes", "Worse implementation", "No difference", "None of the above"], c: "Better implementation outcomes" },
            { q: "Strategic leadership roles include:", o: ["Visionary, architect, coach, catalyst", "Typist, driver, clerk", "Accountant, auditor, lawyer", "None of the above"], c: "Visionary, architect, coach, catalyst" },
            { q: "Emotional intelligence in leadership involves:", o: ["Self-awareness, empathy, social skills", "High IQ only", "Being cold and distant", "None of the above"], c: "Self-awareness, empathy, social skills" },
            { q: "Authentic leadership is:", o: ["Leading with honesty and transparency", "Faking leadership", "Being manipulative", "None of the above"], c: "Leading with honesty and transparency" },
            { q: "Servant leadership focuses on:", o: ["Serving the needs of others", "Serving only self-interest", "Controlling everyone", "None of the above"], c: "Serving the needs of others" },
            { q: "Situational leadership adapts to:", o: ["The maturity and skill level of followers", "One single style for all", "The physical environment only", "None of the above"], c: "The maturity and skill level of followers" },
            { q: "Team dynamics are:", o: ["The psychological processes within a team", "The team's physical movements", "The team's payroll", "None of the above"], c: "The psychological processes within a team" },
            { q: "Collaborative strategy involves:", o: ["Cooperating with other firms for mutual benefit", "Competing at any cost", "Ignoring other firms", "None of the above"], c: "Cooperating with other firms for mutual benefit" },
            { q: "Strategic networking is:", o: ["Building and maintaining relationships for strategic goals", "Using social media only", "Avoiding others", "None of the above"], c: "Building and maintaining relationships for strategic goals" },
            { q: "Conflict resolution techniques include:", o: ["Avoiding, accommodating, competing, collaborating, compromising", "Only competing", "Only avoiding", "None of the above"], c: "Avoiding, accommodating, competing, collaborating, compromising" },
            { q: "Innovation culture encourages:", o: ["Creativity, experimentation, risk-taking", "Following rules strictly only", "Avoiding all risks", "None of the above"], c: "Creativity, experimentation, risk-taking" }
        ]
    },
    {
        setName: "Set 12",
        questions: [
            { q: "Organisational learning levels are:", o: ["Individual, Group, Organisational", "Only individual", "Only group", "None of the above"], c: "Individual, Group, Organisational" },
            { q: "Knowledge sharing is critical for:", o: ["Leveraging an organisation's intellectual capital", "Hiding information", "Reducing innovation", "None of the above"], c: "Leveraging an organisation's intellectual capital" },
            { q: "Performance measurement tools include:", o: ["Financial ratios, KPIs, Balanced Scorecard", "Only income statements", "Only employee attendance", "None of the above"], c: "Financial ratios, KPIs, Balanced Scorecard" },
            { q: "Strategic review meetings should be:", o: ["Regular and action-oriented", "Infrequent and vague", "Optional", "None of the above"], c: "Regular and action-oriented" },
            { q: "External environment monitoring includes:", o: ["Competitors, customers, regulations, technology", "Only internal staff", "Only one supplier", "None of the above"], c: "Competitors, customers, regulations, technology" },
            { q: "Competitive benchmarking is:", o: ["Comparing against direct competitors", "Comparing against internal departments", "Comparing against random firms", "None of the above"], c: "Comparing against direct competitors" },
            { q: "Best practice is:", o: ["A method or technique that has consistently shown results superior to others", "A new untested idea", "The cheapest way", "None of the above"], c: "A method or technique that has consistently shown results superior to others" },
            { q: "Process improvement methodologies include:", o: ["Lean, Six Sigma, TQM", "Only hiring more people", "Increasing waste", "None of the above"], c: "Lean, Six Sigma, TQM" },
            { q: "Customer focus in strategy aims to:", o: ["Understand and meet customer needs for competitive advantage", "Ignore customer feedback", "Increase prices for no reason", "None of the above"], c: "Understand and meet customer needs for competitive advantage" },
            { q: "Market-oriented strategy is driven by:", o: ["Market needs and customer value", "Internal production capacity only", "Owner's whims", "None of the above"], c: "Market needs and customer value" },
            { q: "Strategic vision provides:", o: ["Long-term direction and inspiration", "Short-term tasks", "Daily routines", "None of the above"], c: "Long-term direction and inspiration" },
            { q: "Strategic mission provides:", o: ["Current purpose and scope", "Future direction only", "A detailed checklist", "None of the above"], c: "Current purpose and scope" },
            { q: "Goals and objectives should be:", o: ["SMART (Specific, Measurable, Achievable, Relevant, Time-bound)", "Vague and non-time-bound", "Impossible to reach", "None of the above"], c: "SMART (Specific, Measurable, Achievable, Relevant, Time-bound)" },
            { q: "Strategic priorities are:", o: ["The most important areas to focus on for success", "All areas at once", "No specific areas", "None of the above"], c: "The most important areas to focus on for success" },
            { q: "Resource allocation should align with:", o: ["Strategic priorities", "Random requests", "Old budgets only", "None of the above"], c: "Strategic priorities" },
            { q: "Strategic budget is:", o: ["A financial plan for implementing the strategy", "Daily cash flow", "A past record", "None of the above"], c: "A financial plan for implementing the strategy" },
            { q: "Communication strategy in implementation involves:", o: ["Planning who, what, when, and how to communicate", "Spontaneous emails only", "Keeping everything secret", "None of the above"], c: "Planning who, what, when, and how to communicate" },
            { q: "Training and development support:", o: ["Successful strategy implementation", "Only routine tasks", "Reducing employee skills", "None of the above"], c: "Successful strategy implementation" },
            { q: "Coaching and mentoring help in:", o: ["Developing strategic leaders", "Calculating taxes", "Buying machines", "None of the above"], c: "Developing strategic leaders" },
            { q: "Organisational structure should support:", o: ["Strategy execution", "Bureaucracy only", "Avoiding change", "None of the above"], c: "Strategy execution" },
            { q: "Flat organisational structure has:", o: ["Few levels of management and wide span of control", "Many levels of management", "No management", "None of the above"], c: "Few levels of management and wide span of control" },
            { q: "Hierarchical organisational structure has:", o: ["Multiple levels of management and clear chain of command", "No clear command", "Very few levels", "None of the above"], c: "Multiple levels of management and clear chain of command" },
            { q: "Decentralisation involves:", o: ["Delegating decision-making power to lower levels", "Concentrating power at the top", "No decision-making", "None of the above"], c: "Delegating decision-making power to lower levels" },
            { q: "Centralisation involves:", o: ["Concentrating decision-making power at the top", "Delegating to everyone", "No management", "None of the above"], c: "Concentrating decision-making power at the top" },
            { q: "Standard operating procedures (SOPs) help in:", o: ["Ensuring consistency and efficiency", "Increasing confusion", "Ignoring processes", "None of the above"], c: "Ensuring consistency and efficiency" }
        ]
    },
    {
        setName: "Set 13",
        questions: [
            { q: "Total Factor Productivity is -", o: ["Output / (Labour + Capital + Material)", "Output / Labour", "Output / Capital", "None of the above"], c: "Output / (Labour + Capital + Material)" },
            { q: "One of the example of Pure Service is:", o: ["Teaching", "Aviation", "Hospitality", "None of them"], c: "Teaching" },
            { q: "In the context of BCG Matrix, 'Cash Cow' is a:", o: ["Business with High Market Share and Low growth Rate", "Business with Low Market Share and Low growth Rate", "Business with High Market Share and High growth Rate", "None of the above"], c: "Business with High Market Share and Low growth Rate" },
            { q: "Which of the following is not a strategy for retrenchment?", o: ["Turnaround", "Divestment", "Liquidation", "Diversification"], c: "Diversification" },
            { q: "Productivity is a -", o: ["Quantitate approach", "Qualitative approach", "Management approach", "None of the above"], c: "Quantitate approach" },
            { q: "Expansion strategy can be categorized into -", o: ["Two", "Three", "Four", "Five"], c: "Four" },
            { q: "A question mark (in BCG matrix) has:", o: ["High relative market share in a low-growth market", "Low relative market share in a high-growth market", "Low relative market share in a low-growth market", "High relative market share in a high-growth market"], c: "Low relative market share in a high-growth market" },
            { q: "Which of the following describes 'Value Chain Analysis'?", o: ["Analyzing the sequence of activities that add value to a product", "Analyzing the financial reports only", "Analyzing external threats only", "None of the above"], c: "Analyzing the sequence of activities that add value to a product" },
            { q: "The essential function of Operations Management is:", o: ["Transformation of inputs into outputs", "Managing payroll", "Designing logos", "None of the above"], c: "Transformation of inputs into outputs" },
            { q: "Process selection is a part of:", o: ["Tactical planning", "Strategic planning", "Short-term planning", "None of the above"], c: "Strategic planning" },
            { q: "Wait time is a part of:", o: ["Manufacturing lead time", "Customer service time", "Sales time", "None of the above"], c: "Manufacturing lead time" },
            { q: "Facility layout decision is based on:", o: ["Workflow and material handling", "Number of windows", "Color of paint", "None of the above"], c: "Workflow and material handling" },
            { q: "A work system can be optimized using:", o: ["Method study", "Work measurement", "Both (a) and (b)", "None of above"], c: "Both (a) and (b)" },
            { q: "A successful strategy formulation requires:", o: ["External and internal analysis", "Internal analysis only", "External analysis only", "None of them"], c: "External and internal analysis" },
            { q: "What is 'Strategic Intent'?", o: ["The purpose of an organization's existence and its goals", "A type of insurance", "A financial debt", "None of the above"], c: "The purpose of an organization's existence and its goals" },
            { q: "The acronym SMART stands for:", o: ["Specific, Measurable, Achievable, Relevant, Time-bound", "Small, Manageable, Active, Routine, Task", "Simple, Monetary, Accurate, Reliable, Teamwork", "None of the above"], c: "Specific, Measurable, Achievable, Relevant, Time-bound" },
            { q: "Balanced scorecard perspectives include:", o: ["Financial and Customer", "Internal business processes", "Learning and Growth", "All of the above"], c: "All of the above" },
            { q: "A differentiation strategy aims to:", o: ["Provide unique products/services to customers", "Be the lowest cost producer", "Sell the same product as everyone else", "None of the above"], c: "Provide unique products/services to customers" },
            { q: "Cost leadership strategy aims to:", o: ["Become the lowest-cost producer in the industry", "Provide the most expensive products", "Have the best customer service", "None of the above"], c: "Become the lowest-cost producer in the industry" },
            { q: "Market penetration involves:", o: ["Selling current products in current markets", "Selling new products in current markets", "Selling current products in new markets", "None of the above"], c: "Selling current products in current markets" },
            { q: "Joint Venture is a type of:", o: ["Cooperative strategy", "Competitive strategy", "Red ocean strategy", "None of the above"], c: "Cooperative strategy" },
            { q: "Supply chain management is concerned with:", o: ["Integrating suppliers, manufacturers, and distributors", "Managing only the factory", "Managing only the store", "None of the above"], c: "Integrating suppliers, manufacturers, and distributors" },
            { q: "Six Sigma is a goal of:", o: ["3.4 defects per million opportunities", "10 defects per million", "1 defect per hundred", "None of the above"], c: "3.4 defects per million opportunities" },
            { q: "Quality assurance is:", o: ["Preventive", "Corrective", "Both", "None"], c: "Preventive" },
            { q: "Reliability of a system is:", o: ["The probability that it will work for a given time", "The weight of the system", "The price of the system", "None of the above"], c: "The probability that it will work for a given time" }
        ]
    },
    {
        setName: "Set 14",
        questions: [
            { q: "Break-even point is the level where:", o: ["Total revenue equals total cost", "Profit is maximum", "Loss is maximum", "None of the above"], c: "Total revenue equals total cost" },
            { q: "A Gantt chart is a tool for:", o: ["Project scheduling", "Inventory counting", "Hiring", "None of the above"], c: "Project scheduling" },
            { q: "Maintenance management aims to minimize:", o: ["Total cost of maintenance and breakdown", "Number of machines", "Number of employees", "None of the above"], c: "Total cost of maintenance and breakdown" },
            { q: "Strategic control is a process of:", o: ["Monitoring strategy and making adjustments", "Managing daily work", "Accounting only", "None of the above"], c: "Monitoring strategy and making adjustments" },
            { q: "SWOT analysis is used for:", o: ["Assessing internal and external factors", "Counting stock", "Calculating wages", "None of the above"], c: "Assessing internal and external factors" },
            { q: "Porter's generic strategies include:", o: ["Cost leadership, Differentiation, Focus", "Growth, Stability, Exit", "Marketing, Finance, HR", "None of the above"], c: "Cost leadership, Differentiation, Focus" },
            { q: "The term 'Vision' describes:", o: ["Where an organization wants to be in the future", "What the organization does today", "A list of past achievements", "None of the above"], c: "Where an organization wants to be in the future" },
            { q: "BPR stands for:", o: ["Business Process Reengineering", "Business Plan Report", "Basic Process Result", "None of the above"], c: "Business Process Reengineering" },
            { q: "Productivity can be improved by:", o: ["Reducing input for same output", "Increasing output for same input", "Both (a) and (b)", "None of the above"], c: "Both (a) and (b)" },
            { q: "Total Factor Productivity is:", o: ["The ratio of output to all inputs", "Output divided by labour only", "Input divided by output", "None of the above"], c: "The ratio of output to all inputs" },
            { q: "Wait time in production is:", o: ["The time an item spends waiting for processing", "The time to sell an item", "The time to design an item", "None of the above"], c: "The time an item spends waiting for processing" },
            { q: "Which of the following is not a component of PESTEL analysis?", o: ["Performance", "Economic", "Social", "Technological"], c: "Performance" },
            { q: "Which of the following is NOT a characteristic of a vision statement?", o: ["Brief and concise", "Focused on the current year's budget", "Aspirational and future-oriented", "Inspirational"], c: "Focused on the current year's budget" },
            { q: "Which of the following would be considered a 'Strength' in a SWOT analysis?", o: ["Increasing market competition", "A highly skilled and motivated workforce", "New government regulations", "Old and outdated machinery"], c: "A highly skilled and motivated workforce" },
            { q: "What is the primary purpose of a 'Dog' business unit in the BCG matrix?", o: ["To be the primary source of cash", "To be invested in heavily for growth", "To be harvested or liquidated", "To dominate the market"], c: "To be harvested or liquidated" },
            { q: "What is the first step in the Business Process Reengineering (BPR) cycle?", o: ["Implementation", "Process identification", "Monitoring", "Designing"], c: "Process identification" },
            { q: "Which of the following is NOT an advantage of a 'Differentiation' strategy?", o: ["Higher customer loyalty", "Reduced price sensitivity of customers", "Lowest possible production cost", "Ability to charge a premium price"], c: "Lowest possible production cost" }
        ]
    }
];